5. 데이터 분석 종합 사례

5.1 실습데이터 셋 구성

* < 주요 모듈 임포트 >

In [1]:
import os
import numpy as np
import pandas as pd
import pickle

from datetime import date
from pandas.api.types import is_string_dtype

* < 프로그램 환경구성 >

In [4]:
# 경로설정

# data_path='C:/HANSSAK/SecureGate/download'
# data_path='C:/Users/hazel/Downloads'
data_path='C:/Users/KODIT/downloads'

# 데이터 테이블 최대 변수 갯수 설정
pd.options.display.max_columns = 100

# 소수점 출력 옵션
pd.options.display.float_format = '{:.2f}'.format

In [5]:
# [참고] 해당 경로에 있는 파일 리스트
os.listdir(data_path)

['.ipynb_checkpoints',
 '06-01.ipynb',
 '06-02.ipynb',
 '07-01.ipynb',
 '07-03.ipynb',
 '08-01.ipynb',
 '08-02.ipynb',
 '0_강의자료_BD_모빌리티_1주차_교통카드_21-0827.pdf',
 '0_강의자료_BD_모빌리티_2주차_DTG_21-0904 (1).pdf',
 '0_강의자료_BD_모빌리티_2주차_DTG_21-0904.pdf',
 '0_강의자료_BD_모빌리티_3주차_BMS_21-0915 (1).pdf',
 '0_강의자료_BD_모빌리티_3주차_BMS_21-0915.pdf',
 '0_강의자료_BD_모빌리티_4주차_따릉이_21-0923.pdf',
 '0_실습1_A5_심층신경망 모형을 활용한 대중교통 이용자의 환승시간 추정에 관한 연구.pdf',
 '0_실습2_A7_사업용 자동차 위험운전행동 교통사고 관계 도로 기하구조.pdf',
 '0_실습2_A7_사업용 자동차의 위험운전행동과 교통사고의 관계에 도로 기하구조가 미치는 영향.pdf',
 '0_실습2_B3_교통카드 데이터를 활용한 서울시 고령인구 주요 체류지 및 체류지별 특성.pdf',
 '18-065-spring-2018',
 '18-065-spring-2018.zip',
 '183BA5DC93EC8FDE82908E1139803800D37B04B2 (1).exe',
 '183BA5DC93EC8FDE82908E1139803800D37B04B2.exe',
 '1_BIS자료를이용한중장기버스통행시간예측 (1).pdf',
 '1_BIS자료를이용한중장기버스통행시간예측.pdf',
 '202105141000000039018643.xml',
 '20210608_202842.jpg',
 '20210614_195136.jpg',
 '20210616_202707.jpg',
 '2021학년도+전기+대학원(서울과학기술대학교)+각종+서식.zip',
 '2022년도 일본정부(문부과학성)장학금 연구유학생 추천.zip',
 '2108130956403718220ba7e415be85723eb9d903eded90419cc0ea6e24b8c9a44f5fc54378e7.gif',
 '7-3 모듈만들기.ipynb',
 '7_1.ipynb',
 'Anaconda3-2020.11-Windows-x86_64.exe',
 'Anaconda3-2021.05-Windows-x86_64.exe',
 'AnySign_Installer.exe',
 'apt_capture.png',
 'apt_price_v2.exe',
 'apt_price_v2.py',
 'apt_price_v3.py',
 'apt_price_v3.spec',
 'Attention is All You Need Tutorial (German-English)의 사본',
 'BDCAMSETUP_KOR.EXE',
 'BeatPlayerSetupWeb.exe',
 'blue_train_data.csv.csv의 사본',
 'build',
 'capture.png',
 'CH04 linear_1.pdf',
 'CH05 linear_2.pdf',
 'CH06 linear_3.pdf',
 'chapter04_04.ipynb',
 'chromedriver_win32 (1).zip',
 'chromedriver_win32.zip',
 'Copy_of_presentation2_0524.ipynb',
 'Copy_of_presentation_0524.ipynb',
 'deep-learning-from-scratch-2-master.zip',
 'desktop.ini',
 'dist',
 'drive-download-20210412T092652Z-001',
 'drive-download-20210412T092652Z-001.zip',
 'drive-download-20210510T022637Z-001',
 'drive-download-20210510T022637Z-001.zip',
 'drive-download-20210726T015742Z-001',
 'drive-download-20210726T015742Z-001.zip',
 'drive-download-20210819T023929Z-001.zip',
 'drive-download-20210819T025651Z-001.zip',
 'drive-download-20210924T040644Z-001.zip',
 'DT 연수 프로그램',
 'DT_응용사례_v1.1 (1).zip',
 'DT_응용사례_v1.1.zip',
 'equations_and_figures_2.zip',
 'Free T 기기&유심변경신청서 (1).jpg',
 'Free T 기기&유심변경신청서.jpg',
 'GE 사례 동영상.mp4',
 'General.zip',
 'GeoJSON_and_choropleth.ipynb',
 'GitHubDesktopSetup.exe',
 'GOMMixKor_1.1.0.4_20200417.EXE',
 'HW01.pdf',
 'hw3_seq2seq.py',
 'HW_word2vec.ipynb',
 'ICT_REPORTX_SETUP.exe',
 'import.tex',
 'Inspector (인터넷)',
 'Inspector (인터넷).exe',
 'Inspector (인터넷).zip',
 'KakaoTalk_Setup.exe',
 'KB_apt_capture.png',
 'KODIT_APT_PRICE.exe.spec',
 'KODIT_APT_PRICE.spec',
 'KODIT_APT_PRICE_v1.1.exe',
 'kodit_apt_price_v1.1.py',
 'kodit_apt_price_v1.1.spec',
 'kodit_apt_price_v1.exe',
 'kodit_apt_price_v1.py',
 'kodit_apt_price_v1.spec',
 'kodit_apt_price_v1.zip',
 'kodit_apt_price_v2.1.py',
 'kodit_apt_price_v2.1.spec',
 'kodit_atp_price_v2.0.spec',
 'kor-eng.zip',
 'KSCertRelay_nx_Installer_32bit.exe',
 'Leer!!.txt',
 'libegl.dll',
 'libegl.zip',
 'ManualLauncherEx.exe',
 'map_capture.png',
 'n.spec',
 'NanumGothic.ttf',
 'Nanum_Gothic',
 'Nanum_Gothic.zip',
 'Nanum_Gothic_Coding',
 'Nanum_Gothic_Coding.zip',
 'NTS_eTaxInvoice (1).html',
 'NTS_eTaxInvoice (2).html',
 'NTS_eTaxInvoice.html',
 'pandas5.ipynb',
 'pandas_4.ipynb',
 'pandas_4_수정.ipynb',
 'Pandas_Data_DL&UL (1).ipynb',
 'Pandas_Data_DL&UL.ipynb',
 'picpick_inst_kr.exe',
 'pycharm-edu-2020.3.4.exe',
 'pycharm-professional-2020.3.3.exe',
 'qwindows.zip',
 'README.txt',
 'reat_tr_capture.png',
 'res-18-010-spring-2020',
 'res-18-010-spring-2020.zip',
 'Saferzone_v5.0_20191016.exe',
 'sc2_ch1 (1).ipynb',
 'sc2_ch1.ipynb',
 'sc2_ch2 (1).ipynb',
 'sc2_ch2.ipynb',
 'sc2_ch4(20210331).ipynb',
 'sc2_ch5(20210414).ipynb',
 'sc2_ch7 (1).ipynb',
 'sc2_ch7.ipynb',
 'sc2_ch8(20210526).ipynb',
 'Setup_ePageSaferRT (1).exe',
 'Setup_ePageSaferRT.exe',
 'SOL AL_Apl_Bretscher_3ed_elsolucionario.blogspot.com',
 'SOL AL_Apl_Bretscher_3ed_elsolucionario.blogspot.com.rar',
 'TDClientforWindowsAgentNX_4.9.0.5.exe',
 'Teams_windows_x64 (1).exe',
 'Teams_windows_x64 (2).exe',
 'Teams_windows_x64.exe',
 'temp.json',
 'temp_1616987946046.-1299207563.jpeg',
 'temp_1616987985641.1886660292.jpeg',
 'temp_1616988011172.678426062.jpeg',
 'temp_1616988029792.-213272946.jpeg',
 'temp_1616988057281.-1181086768.jpeg',
 'temp_1616988072569.1838815029.jpeg',
 'temp_1616988090134.-1168425798.jpeg',
 'temp_1616988112435.-1308863531.jpeg',
 'temp_1616988134583.-309553415.jpeg',
 'temp_1616988156491.1747779551.jpeg',
 'temp_1616988174036.-4329745.jpeg',
 'temp_1616988197923.2072186799.jpeg',
 'temp_1616988214518.-1999478264.jpeg',
 'test.ipynb',
 'transformer 실습 (1).zip',
 'transformer 실습.zip',
 'untitled0.py',
 'untitled2.py',
 'untitled3.py',
 'untitled4.py',
 'untitled5.py',
 'untitled6.py',
 'untitled7.py',
 'untitled8.py',
 'untitled9.py',
 'veraport-g3-x64.exe',
 'Vrew-0.8.21.exe',
 'word2vec.ipynb',
 'Xshell-7.0.0073.exe',
 'Zoom_cm_ds_mFz7nEaorZWr94m9E-DCwjk9-9SG8-elOQqM@hjpJ20M-y3agn+Wv_kc4e6c5f3f595c7f1_.exe',
 '[Dataset] 작업형 제1유형',
 '[Dataset] 작업형 제1유형.zip',
 '[Dataset] 작업형 제2유형',
 '[Dataset] 작업형 제2유형.zip',
 '[실기문제]',
 '[실기문제].zip',
 '__pycache__',
 '¡Visita el blog!.URL',
 '경희대학교.zip',
 '고려대학교.zip',
 '교안 예제_v1.2.ipynb',
 '기술지도사 제출자료',
 '답안지.zip',
 '데이타수집_크롤링.py',
 '동국대학교.zip',
 '보증상품분석.ipynb',
 '보증상품분석_v5.ipynb',
 '부동산 시세정보 조회 시연 v3.mp4',
 '부동산 시세조회 가이드 v2.0.mp4',
 '부동산 시세조회 프로그램 (1).png',
 '부동산 시세조회 프로그램 (1).zip',
 '부동산 시세조회 프로그램 (10).png',
 '부동산 시세조회 프로그램 (11).png',
 '부동산 시세조회 프로그램 (12).png',
 '부동산 시세조회 프로그램 (13).png',
 '부동산 시세조회 프로그램 (2).png',
 '부동산 시세조회 프로그램 (3).png',
 '부동산 시세조회 프로그램 (4).png',
 '부동산 시세조회 프로그램 (5).png',
 '부동산 시세조회 프로그램 (6).png',
 '부동산 시세조회 프로그램 (7).png',
 '부동산 시세조회 프로그램 (8).png',
 '부동산 시세조회 프로그램 (9).png',
 '부동산 시세조회 프로그램.png',
 '부동산 시세조회 프로그램.zip',
 '부동산 시세조회_게시용.zip',
 '부동산시세조사_v3.py',
 '빅데이타프로그래밍_03_02_부울과 조건문 (1).ipynb',
 '빅데이타프로그래밍_03_02_부울과 조건문.ipynb',
 '빅데이터프로그래밍_과제#1_G20214046_장홍진.ipynb',
 '빅데이터프로그래밍_과제#3_G20214604_장홍진',
 '빅데이터프로그래밍_과제#3_G20214604_장홍진.zip',
 '빅데이터프로그래밍_과제3_생활인구_참조답안.ipynb',
 '서울과학기술대학교.zip',
 '서울시립대학교.zip',
 '숙명여자대학교',
 '숙명여자대학교.zip',
 '스타벅스_매장.ipynb',
 '실습1_06_서울 공공자전거 신규 대여소를 위한 수요량 예측 분석.pdf',
 '실습2_09_공공자전거 쏠림현상 해소 동적 재배치 라우팅 창원시 사례.pdf',
 '실습데이터_보증_부실.xlsx',
 '실행화면1.jpg',
 '실행화면2.jpg',
 '연습문제.ipynb',
 '예외_고급.ipynb',
 '이미지 1 (1).jpg',
 '이미지 1.jpg',
 '이미지 2.jpg',
 '이미지 22.jpg',
 '이미지 3.jpg',
 '이미지 4.jpg',
 '이미지 5.jpg',
 '이미지 7.jpg',
 '중간고사 답지_G20214604_장홍진.jpg',
 '중앙대학교.zip',
 '지난수업자료',
 '지난수업자료.zip',
 '지학사 확률과통계 교과서.vol1.egg',
 '지학사 확률과통계 교과서.vol2.egg',
 '지학사 확률과통계 교과서.vol3.egg',
 '지학사 확률과통계 교과서.vol4.egg',
 '지학사 확률과통계 교과서.vol5.egg',
 '지학사 확률과통계 교과서.vol6.egg',
 '지학사 확률과통계 교과서.vol7.egg',
 '지학사 확률과통계 교과서.vol8.egg',
 '클래스 (1).ipynb',
 '클래스.ipynb',
 '텐서플로우의 이해(예제)',
 '텐서플로우의 이해(예제).zip',
 '특수문자 입력기.zip',
 '파이썬패키지.txt',
 '프로그래밍_발표용(외부모듈) (1).ipynb',
 '프로그래밍_발표용(외부모듈).ipynb',
 '프린트',
 '프린트-20210628T032419Z-001.zip',
 '한국부동산원 시세조회_v1.py',
 '한국부동산원 시세조회_v2.py',
 '한국부동산원 시세조회_v3.py',
 '한국외국어대학교.zip',
 '한양대학교.zip']

* < 엑셀 데이터 불러오기 >

In [6]:
# 데이터 불러오기

# 보증데이터
boj_data_2019 = pd.read_excel(data_path + '/data_QCU_0013_통합_보증_취급_명세_2019.xlsx')

# 부실데이터
busil_data_2019 = pd.read_excel(data_path + '/data_QCU_0001_통합_관리_부실명세_2019.xlsx')
busil_data_2020 = pd.read_excel(data_path + '/data_QCU_0001_통합_관리_부실명세_2020.xlsx')

* < 파이썬 데이터 저장 >

In [7]:
# 데이터 저장

# 보증데이터
boj_data_2019.to_pickle(data_path + '/boj_data_2019.pkl')

# 부실데이터
busil_data_2019.to_pickle(data_path + '/busil_data_2019.pkl')
busil_data_2020.to_pickle(data_path + '/busil_data_2020.pkl')

* < 보증 데이터 셋 정리 >

In [11]:
# 보증데이터 불러오기
boj_data_2019 = pd.read_pickle(data_path + '/boj_data_2019.pkl')
boj_data_2019.info()

# 보증데이터 변수 리스트 확인
list=boj_data_2019.columns.to_list()
list

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 265999 entries, 0 to 265998
Columns: 105 entries, 원장번호 to 신규증액금액
dtypes: datetime64[ns](1), float64(19), int64(9), object(76)
memory usage: 213.1+ MB

['원장번호',
 '보증취급일자',
 '실행구분',
 '원장진행상태',
 '보증관할영업본부명',
 '신용보증관할부점명',
 '취급영업본부',
 '취급부점',
 '고객번호',
 '수도권소재지기업구분명',
 '수도권소재지기업구분명_취급시점',
 '수도권소재지기업구분지역명',
 '수도권소재지기업구분지역명_취급시점',
 '순보증사용일수',
 '최종업종차수',
 '최종업종코드',
 '최종업종명',
 '최종업종차수_취급시점',
 '최종업종코드_취급시점',
 '최종업종명_취급시점',
 '설립일자',
 '판매품목1',
 '판매품목2',
 '기업규모',
 '기업규모_취급시점',
 '기업규모_최신',
 '원장최초취급일자',
 '상담일자',
 '접수일자',
 '승인일자',
 '취급일자',
 '전액해지일자',
 '보증시작일자',
 '보증종료일자',
 '거래방법',
 '건별구분',
 '취급종류',
 '보증서형태',
 '직위재구분',
 '주채무과목코드',
 '주채무과목',
 '자금용도',
 '보증기한',
 '심사종류',
 '보증잔액',
 '심사서상_기보보증잔액',
 '심사서상_재단보증잔액',
 '심사체크리스트저촉건수',
 '체크리스트저촉1',
 '체크리스트저촉2',
 '체크리스트저촉3',
 '체크리스트저촉4',
 '체크리스트저촉5',
 '체크리스트저촉6',
 '체크리스트저촉7',
 '체크리스트저촉8',
 '체크리스트저촉9',
 '체크리스트저촉10',
 '상시직원수_취급일',
 '상시직원수_기준일',
 '피보험자수_취급월',
 '피보험자수_기준월',
 '피보험자수_전년말',
 '피보험자수_전전년말',
 '피보험자수_전전전년말',
 '주소구분_지역구분명',
 '주소구분_시군구명',
 '사업장소재지',
 '기업가치평가금액',
 '조사기준일자',
 '평가모형',
 '종합신용등급',
 '지식자산평가GR등급',
 '기술평가TR등급',
 '기업가치FV등급',
 '보증심사등급',
 '미래성장기업군',
 '책임경영등급코드',
 '상품정보_기업특성개수',
 '상품정보_자금특성개수',
 '1_상품코드',
 '2_상품코드',
 '3_상품코드',
 '4_상품코드',
 '5_상품코드',
 '6_상품코드',
 '7_상품코드',
 '8_상품코드',
 '9_상품코드',
 '10_상품코드',
 '(취급시)_당기_최종결산일자',
 '(취급시)_전기_최종결산일자',
 '(취급시)_당기_매출액',
 '(취급시)_전기_매출액',
 '(취급시)_당기_자산총계',
 '(취급시)_전기_자산총계',
 '(취급시)_당기_경상개발비',
 '(취급시)_전기_경상개발비',
 '(취급시)_당기_부채비율',
 '(취급시)_전기_부채비율',
 '(취급시)_당기_현금흐름등급',
 '(취급시)_전기_현금흐름등급',
 '재무제표수정여부',
 '취급금액',
 '신규증액금액']

* 조건에 맞는 행 선택

In [12]:
# 신규증액 데이터 선택
boj_data2 = boj_data_2019[boj_data_2019['신규증액금액']>0]

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41190 entries, 1 to 265987
Columns: 106 entries, 원장번호 to CNT
dtypes: datetime64[ns](1), float64(19), int64(10), object(76)
memory usage: 33.6+ MB

<ipython-input-12-895297a75621>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  boj_data2['CNT'] = 1

* 신규 변수 생성

In [ ]:
# 업체수 계산을 위한 변수 설정
boj_data2['CNT'] = 1
boj_data2.info()

* < 부실 데이터 셋 정리 >

In [8]:
# 부실데이터 불러오기
busil_data_2019= pd.read_pickle(data_path + '/busil_data_2019.pkl')
busil_data_2019.info()
busil_data_2020= pd.read_pickle(data_path + '/busil_data_2020.pkl')
busil_data_2020.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15789 entries, 0 to 15788
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   고객번호                15789 non-null  int64
 1   신용보증관할부점코드          15789 non-null  object
 2   보증번호                15789 non-null  object
 3   개인법인사업자구분명          15789 non-null  object
 4   부실발생일자              15789 non-null  object
 5   부실정상화일자             15789 non-null  object
 6   수도권소재지기업구분지역명_처리시점  15789 non-null  object
 7   최종업종코드_처리시점         15789 non-null  object
 8   최종업종차수_처리시점         15789 non-null  int64
 9   직위재구분               15789 non-null  object
 10  부실사유                15789 non-null  object
 11  취급종류                15789 non-null  object
 12  직접위탁부실발생금액_고객       15789 non-null  int64
 13  당초부실처리부점코드_고객       15789 non-null  object
 14  단기고액구분              1964 non-null   object
 15  부실사유발생일자            15789 non-null  object
 16  최초신규원장취급일자          15789 non-null  object
 17  최종신규증액보증거래일자        15789 non-null  object
 18  최종신규증액보증한도승인일자      15789 non-null  object
 19  최근신규원장취급일자          15789 non-null  object
 20  연대보증입보면제원장여부        15789 non-null  object
 21  자금용도                15789 non-null  object
 22  기업규모명               15737 non-null  object
 23  부실발생금액              15789 non-null  int64
 24  부실순증금액              15789 non-null  int64
 25  부실발생건수              15789 non-null  int64
 26  부실순증건수              15789 non-null  int64
 27  기타원장구분              0 non-null      float64
dtypes: float64(1), int64(7), object(20)
memory usage: 3.4+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14255 entries, 0 to 14254
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   고객번호                14255 non-null  int64
 1   신용보증관할부점코드          14255 non-null  object
 2   보증번호                14255 non-null  object
 3   개인법인사업자구분명          14255 non-null  object
 4   부실발생일자              14255 non-null  object
 5   부실정상화일자             14255 non-null  object
 6   수도권소재지기업구분지역명_처리시점  14255 non-null  object
 7   최종업종코드_처리시점         14255 non-null  object
 8   최종업종차수_처리시점         14255 non-null  int64
 9   직위재구분               14255 non-null  object
 10  부실사유                14255 non-null  object
 11  취급종류                14255 non-null  object
 12  직접위탁부실발생금액_고객       14255 non-null  int64
 13  당초부실처리부점코드_고객       14255 non-null  object
 14  단기고액구분              1896 non-null   object
 15  부실사유발생일자            14255 non-null  object
 16  최초신규원장취급일자          14255 non-null  object
 17  최종신규증액보증거래일자        14255 non-null  object
 18  최종신규증액보증한도승인일자      14255 non-null  object
 19  최근신규원장취급일자          14255 non-null  object
 20  연대보증입보면제원장여부        14255 non-null  object
 21  자금용도                14255 non-null  object
 22  기업규모명               13288 non-null  object
 23  부실발생금액              14255 non-null  int64
 24  부실순증금액              14255 non-null  int64
 25  부실발생건수              14255 non-null  int64
 26  부실순증건수              14255 non-null  int64
 27  기타원장구분              1074 non-null   object
dtypes: int64(7), object(21)
memory usage: 3.0+ MB

* 데이터 병합 (세로)

In [9]:
# 부실데이터 병합
busil_data=pd.concat([busil_data_2019, busil_data_2020])
busil_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30044 entries, 0 to 14254
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   고객번호                30044 non-null  int64
 1   신용보증관할부점코드          30044 non-null  object
 2   보증번호                30044 non-null  object
 3   개인법인사업자구분명          30044 non-null  object
 4   부실발생일자              30044 non-null  object
 5   부실정상화일자             30044 non-null  object
 6   수도권소재지기업구분지역명_처리시점  30044 non-null  object
 7   최종업종코드_처리시점         30044 non-null  object
 8   최종업종차수_처리시점         30044 non-null  int64
 9   직위재구분               30044 non-null  object
 10  부실사유                30044 non-null  object
 11  취급종류                30044 non-null  object
 12  직접위탁부실발생금액_고객       30044 non-null  int64
 13  당초부실처리부점코드_고객       30044 non-null  object
 14  단기고액구분              3860 non-null   object
 15  부실사유발생일자            30044 non-null  object
 16  최초신규원장취급일자          30044 non-null  object
 17  최종신규증액보증거래일자        30044 non-null  object
 18  최종신규증액보증한도승인일자      30044 non-null  object
 19  최근신규원장취급일자          30044 non-null  object
 20  연대보증입보면제원장여부        30044 non-null  object
 21  자금용도                30044 non-null  object
 22  기업규모명               29025 non-null  object
 23  부실발생금액              30044 non-null  int64
 24  부실순증금액              30044 non-null  int64
 25  부실발생건수              30044 non-null  int64
 26  부실순증건수              30044 non-null  int64
 27  기타원장구분              1074 non-null   object
dtypes: int64(7), object(21)
memory usage: 6.6+ MB

* 필요한 변수 선택

In [10]:
# 부실데이터 필요 칼럼 추출
busil_data2 = busil_data.loc[:,['고객번호','부실사유발생일자','직접위탁부실발생금액_고객']]
busil_data2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 30044 entries, 0 to 14254
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   고객번호           30044 non-null  int64
 1   부실사유발생일자       30044 non-null  object
 2   직접위탁부실발생금액_고객  30044 non-null  int64
dtypes: int64(2), object(1)
memory usage: 938.9+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 16647 entries, 0 to 14254
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   고객번호           16647 non-null  int64
 1   부실사유발생일자       16647 non-null  object
 2   직접위탁부실발생금액_고객  16647 non-null  int64
dtypes: int64(2), object(1)
memory usage: 520.2+ KB

* 중복데이터 제거

In [ ]:
# 부실데이터 중복 제거
busil_data3 = busil_data2.drop_duplicates()
busil_data3.info()

* < 분석 데이터 셋 정리 >

보증데이터 + 부실데이터 연결

* 데이터 병합 (가로)

In [13]:
# merge 방법
base_data_m = pd.merge(boj_data2, busil_data3, how='left', left_on='고객번호', right_on='고객번호')
base_data_m.info()

# join 방법
base_data_j = boj_data2.join(busil_data3.set_index('고객번호'),on='고객번호')
base_data_j.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41197 entries, 0 to 41196
Columns: 108 entries, 원장번호 to 직접위탁부실발생금액_고객
dtypes: datetime64[ns](1), float64(20), int64(10), object(77)
memory usage: 34.3+ MB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 41197 entries, 1 to 265987
Columns: 108 entries, 원장번호 to 직접위탁부실발생금액_고객
dtypes: datetime64[ns](1), float64(20), int64(10), object(77)
memory usage: 34.3+ MB

* 필요한 변수 선택

In [14]:
# 분석데이터 필요 칼럼 추출
base_data2 = base_data_m.loc[:,
                             ['고객번호','최종업종코드','설립일자','기업규모','사업장소재지','판매품목1','판매품목2','피보험자수_취급월', '피보험자수_기준월', '피보험자수_전년말','피보험자수_전전년말','피보험자수_전전전년말', # 고객기본정보
                              '원장번호','취급부점','보증취급일자','직위재구분','자금용도','주채무과목','순보증사용일수','신규증액금액','심사서상_기보보증잔액','심사서상_재단보증잔액','상품정보_기업특성개수','상품정보_자금특성개수','CNT', # 보증취급정보
                              '심사종류','심사체크리스트저촉건수', '체크리스트저촉1','체크리스트저촉2','체크리스트저촉3','체크리스트저촉4','체크리스트저촉5','체크리스트저촉6','체크리스트저촉7','체크리스트저촉8','체크리스트저촉9','체크리스트저촉10',  # 심사 관련 정보
                              '조사기준일자','평가모형','종합신용등급','지식자산평가GR등급','기술평가TR등급','기업가치FV등급','보증심사등급','미래성장기업군','책임경영등급코드', # 평가 관련 정보
                              '(취급시)_당기_최종결산일자','(취급시)_당기_매출액','(취급시)_전기_매출액','(취급시)_당기_자산총계','(취급시)_전기_자산총계','(취급시)_당기_경상개발비','(취급시)_전기_경상개발비','(취급시)_당기_부채비율','(취급시)_전기_부채비율','(취급시)_당기_현금흐름등급','(취급시)_전기_현금흐름등급', # 재무정보
                              '부실사유발생일자','직접위탁부실발생금액_고객'] # 부실정보
                            ]  
base_data2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41197 entries, 0 to 41196
Data columns (total 59 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   고객번호             41197 non-null  int64
 1   최종업종코드           41197 non-null  object
 2   설립일자             41197 non-null  datetime64[ns]
 3   기업규모             41018 non-null  object
 4   사업장소재지           41197 non-null  object
 5   판매품목1            34181 non-null  object
 6   판매품목2            868 non-null    object
 7   피보험자수_취급월        41171 non-null  float64
 8   피보험자수_기준월        41171 non-null  float64
 9   피보험자수_전년말        11977 non-null  float64
 10  피보험자수_전전년말       8755 non-null   float64
 11  피보험자수_전전전년말      6832 non-null   float64
 12  원장번호             41197 non-null  object
 13  취급부점             41197 non-null  object
 14  보증취급일자           41197 non-null  object
 15  직위재구분            41197 non-null  object
 16  자금용도             41197 non-null  object
 17  주채무과목            41197 non-null  object
 18  순보증사용일수          41197 non-null  int64
 19  신규증액금액           41197 non-null  int64
 20  심사서상_기보보증잔액      40906 non-null  float64
 21  심사서상_재단보증잔액      40906 non-null  float64
 22  상품정보_기업특성개수      29188 non-null  float64
 23  상품정보_자금특성개수      36710 non-null  float64
 24  CNT              41197 non-null  int64
 25  심사종류             40006 non-null  object
 26  심사체크리스트저촉건수      9426 non-null   float64
 27  체크리스트저촉1         9426 non-null   object
 28  체크리스트저촉2         9426 non-null   object
 29  체크리스트저촉3         9426 non-null   object
 30  체크리스트저촉4         9426 non-null   object
 31  체크리스트저촉5         9426 non-null   object
 32  체크리스트저촉6         9426 non-null   object
 33  체크리스트저촉7         9426 non-null   object
 34  체크리스트저촉8         9426 non-null   object
 35  체크리스트저촉9         9426 non-null   object
 36  체크리스트저촉10        9426 non-null   object
 37  조사기준일자           40898 non-null  object
 38  평가모형             40898 non-null  object
 39  종합신용등급           40898 non-null  object
 40  지식자산평가GR등급       31880 non-null  object
 41  기술평가TR등급         2203 non-null   object
 42  기업가치FV등급         7294 non-null   object
 43  보증심사등급           35010 non-null  object
 44  미래성장기업군          35009 non-null  object
 45  책임경영등급코드         16665 non-null  object
 46  (취급시)_당기_최종결산일자  33042 non-null  object
 47  (취급시)_당기_매출액     32310 non-null  float64
 48  (취급시)_전기_매출액     27135 non-null  float64
 49  (취급시)_당기_자산총계    33032 non-null  float64
 50  (취급시)_전기_자산총계    27807 non-null  float64
 51  (취급시)_당기_경상개발비   2656 non-null   float64
 52  (취급시)_전기_경상개발비   1995 non-null   float64
 53  (취급시)_당기_부채비율    22297 non-null  float64
 54  (취급시)_전기_부채비율    10561 non-null  float64
 55  (취급시)_당기_현금흐름등급  16541 non-null  object
 56  (취급시)_전기_현금흐름등급  661 non-null    object
 57  부실사유발생일자         901 non-null    object
 58  직접위탁부실발생금액_고객    901 non-null    float64
dtypes: datetime64[ns](1), float64(19), int64(4), object(35)
memory usage: 18.9+ MB

* 신규 변수 생성

In [ ]:
# 부실발생금액이 1보다 크면 부실여부 1로, 아니면 0으로 처리
base_data2['부실여부'] = [1 if i > 0 else 0 for i in base_data2['직접위탁부실발생금액_고객']]

* 변수 이름 변경

In [16]:
# 종합신용등급 변수명 변경
base_data2.rename(columns={'종합신용등급':'grade'},inplace=True)
base_data2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41197 entries, 0 to 41196
Data columns (total 60 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   고객번호             41197 non-null  int64
 1   최종업종코드           41197 non-null  object
 2   설립일자             41197 non-null  datetime64[ns]
 3   기업규모             41018 non-null  object
 4   사업장소재지           41197 non-null  object
 5   판매품목1            34181 non-null  object
 6   판매품목2            868 non-null    object
 7   피보험자수_취급월        41171 non-null  float64
 8   피보험자수_기준월        41171 non-null  float64
 9   피보험자수_전년말        11977 non-null  float64
 10  피보험자수_전전년말       8755 non-null   float64
 11  피보험자수_전전전년말      6832 non-null   float64
 12  원장번호             41197 non-null  object
 13  취급부점             41197 non-null  object
 14  보증취급일자           41197 non-null  object
 15  직위재구분            41197 non-null  object
 16  자금용도             41197 non-null  object
 17  주채무과목            41197 non-null  object
 18  순보증사용일수          41197 non-null  int64
 19  신규증액금액           41197 non-null  int64
 20  심사서상_기보보증잔액      40906 non-null  float64
 21  심사서상_재단보증잔액      40906 non-null  float64
 22  상품정보_기업특성개수      29188 non-null  float64
 23  상품정보_자금특성개수      36710 non-null  float64
 24  CNT              41197 non-null  int64
 25  심사종류             40006 non-null  object
 26  심사체크리스트저촉건수      9426 non-null   float64
 27  체크리스트저촉1         9426 non-null   object
 28  체크리스트저촉2         9426 non-null   object
 29  체크리스트저촉3         9426 non-null   object
 30  체크리스트저촉4         9426 non-null   object
 31  체크리스트저촉5         9426 non-null   object
 32  체크리스트저촉6         9426 non-null   object
 33  체크리스트저촉7         9426 non-null   object
 34  체크리스트저촉8         9426 non-null   object
 35  체크리스트저촉9         9426 non-null   object
 36  체크리스트저촉10        9426 non-null   object
 37  조사기준일자           40898 non-null  object
 38  평가모형             40898 non-null  object
 39  grade            40898 non-null  object
 40  지식자산평가GR등급       31880 non-null  object
 41  기술평가TR등급         2203 non-null   object
 42  기업가치FV등급         7294 non-null   object
 43  보증심사등급           35010 non-null  object
 44  미래성장기업군          35009 non-null  object
 45  책임경영등급코드         16665 non-null  object
 46  (취급시)_당기_최종결산일자  33042 non-null  object
 47  (취급시)_당기_매출액     32310 non-null  float64
 48  (취급시)_전기_매출액     27135 non-null  float64
 49  (취급시)_당기_자산총계    33032 non-null  float64
 50  (취급시)_전기_자산총계    27807 non-null  float64
 51  (취급시)_당기_경상개발비   2656 non-null   float64
 52  (취급시)_전기_경상개발비   1995 non-null   float64
 53  (취급시)_당기_부채비율    22297 non-null  float64
 54  (취급시)_전기_부채비율    10561 non-null  float64
 55  (취급시)_당기_현금흐름등급  16541 non-null  object
 56  (취급시)_전기_현금흐름등급  661 non-null    object
 57  부실사유발생일자         901 non-null    object
 58  직접위탁부실발생금액_고객    901 non-null    float64
 59  부실여부             41197 non-null  int64
dtypes: datetime64[ns](1), float64(19), int64(5), object(35)
memory usage: 19.2+ MB

In [15]:
# 분석 데이터 셋 저장
base_data2.to_pickle(data_path + '/base_data2.pkl')
base_data2.to_excel(data_path + '/보증특성분석 데이터.xlsx')

* 날짜 데이터 변환 및 활용

In [45]:
# <날짜변수 생성>
# 날짜로 보이는 변수 타입 확인
print(is_string_dtype(base_data2['설립일자']))
print(is_string_dtype(base_data2['보증취급일자']))

# 문자열을 날짜변수로 변환
base_data2['설립일자'] = pd.to_datetime(base_data2['설립일자']) 

base_data2['보증취급일자'] = pd.to_datetime(base_data2['보증취급일자'])
base_data2['부실사유발생일자'] = pd.to_datetime(base_data2['부실사유발생일자'])

# 날짜변수 계산
base_data2['업력'] = base_data2['보증취급일자'] - base_data2['설립일자'] 
base_data2['부실기간'] = base_data2['부실사유발생일자'] - base_data2['보증취급일자'] 

base_data2.head(2)

False
False

,고객번호,최종업종코드,설립일자,기업규모,사업장소재지,판매품목1,판매품목2,피보험자수_취급월,피보험자수_기준월,피보험자수_전년말,피보험자수_전전년말,피보험자수_전전전년말,원장번호,취급부점,보증취급일자,직위재구분,자금용도,주채무과목,순보증사용일수,신규증액금액,심사서상_기보보증잔액,심사서상_재단보증잔액,상품정보_기업특성개수,상품정보_자금특성개수,CNT,심사종류,심사체크리스트저촉건수,체크리스트저촉1,체크리스트저촉2,체크리스트저촉3,체크리스트저촉4,체크리스트저촉5,체크리스트저촉6,체크리스트저촉7,체크리스트저촉8,체크리스트저촉9,체크리스트저촉10,조사기준일자,평가모형,grade,지식자산평가GR등급,기술평가TR등급,기업가치FV등급,보증심사등급,미래성장기업군,책임경영등급코드,(취급시)_당기_최종결산일자,(취급시)_당기_매출액,(취급시)_전기_매출액,(취급시)_당기_자산총계,(취급시)_전기_자산총계,(취급시)_당기_경상개발비,(취급시)_전기_경상개발비,(취급시)_당기_부채비율,(취급시)_전기_부채비율,(취급시)_당기_현금흐름등급,(취급시)_전기_현금흐름등급,부실사유발생일자,직접위탁부실발생금액_고객,부실여부,피보험자수_구분,지역구분,업력,부실기간,고객번호1,고객번호2,a,b,c,고객번호3,고객번호4,수도권여부,신규증액금액_comma
0,76691713,C32029,2013-12-24,소기업,부산 체육공원로,가구 제조업,NaN,1.00,1.00,1.00,NaN,NaN,TBF201813649,동래,2019-01-02,직접,운전자금,기업일반자금대출,30,90000000,0.00,45.00,NaN,NaN,1,일반심사(창업기업),1.00,미래상환능력 평가등급이 E등급 이하 (최근2개년 EBITDA이자보상배율이 계속 1미만),,,,,,,,,,2018-12-27,KRS-S,KR9,GR-6,NaN,NaN,K9,III군,NaN,2020-12-31,348.00,367.00,100.00,149.00,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,0,5인이하,부산,1835 days,NaT,076691713,07-669-1713,07,669,1713,07-669-1713,07-669-1713,비수도권,"90,000,000"
1,76553566,R91210,1987-04-11,소기업,경기 장흥면,두리랜드 운영,NaN,2.00,1.00,2.00,NaN,NaN,THS201912347,의정부,2019-01-02,직접,시설자금,각종시설자금대출,49,5000000000,0.00,50.00,NaN,1.00,1,NaN,3.00,당기 매출액대비 총차입금비율이 70% 초과,당기 매출액대비 운전자금차입금비율이 50% 초과,"기업가치가 ""0""이하인 기업 또는 기업가치평가등급이 ""FV-10""인 기업",,,,,,,,2018-11-05,KRS-C,KR9,GR-4,NaN,FV-10,K11,III군,NaN,2017-12-31,868.00,589.00,8606.00,6971.00,NaN,NaN,48.55,43.29,CR-5,CR-5,NaT,NaN,0,5인이하,경기,11589 days,NaT,076553566,07-655-3566,07,655,3566,07-655-3566,07-655-3566,수도권,"5,000,000,000"

* 문자열 형태 변환 : 고객번호(숫자형)를 문자형으로 변환

In [28]:
# <문자열 형태 변환>

# 빈 자리수 0으로 채우기 1 : zfill()
base_data2['고객번호1'] = base_data2['고객번호'].astype(str) # 숫자변수를 문자열 변수로 전환
base_data2['고객번호1'] = base_data2['고객번호1'].str.zfill(width=9) # 9자리 중 빈 자리를 0으로 채움

# 빈 자리수 0으로 채우기 2 : format()
base_data2['고객번호2'] = base_data2['고객번호'].apply(lambda x: "{0:>09d}".format(x)) # 9자리 중 빈 자리를 왼쪽부터 채움 (오른쪽으로 숫자 밀림)

# 고객번호 슬라이싱 후 변수 생성
a=base_data2['고객번호1'].str[:2]

base_data2['a']=base_data2['고객번호1'].str[:2]
base_data2['b']=base_data2['고객번호1'].str[2:5]
base_data2['c']=base_data2['고객번호1'].str[5:9]

# - 로 연결하기 1 : + 기호 사용
base_data2['고객번호3'] = a + '-' + base_data2['b'] + '-' + base_data2['고객번호1'].str[5:9]

# - 로 연결하기 2 : join() 
base_data2['고객번호4'] =base_data2[['a','b','c']].apply(lambda x : '-'.join(x),axis=1)
base_data2

,고객번호,최종업종코드,설립일자,기업규모,사업장소재지,판매품목1,판매품목2,피보험자수_취급월,피보험자수_기준월,피보험자수_전년말,피보험자수_전전년말,피보험자수_전전전년말,원장번호,취급부점,보증취급일자,직위재구분,자금용도,주채무과목,순보증사용일수,신규증액금액,심사서상_기보보증잔액,심사서상_재단보증잔액,상품정보_기업특성개수,상품정보_자금특성개수,CNT,심사종류,심사체크리스트저촉건수,체크리스트저촉1,체크리스트저촉2,체크리스트저촉3,체크리스트저촉4,체크리스트저촉5,체크리스트저촉6,체크리스트저촉7,체크리스트저촉8,체크리스트저촉9,체크리스트저촉10,조사기준일자,평가모형,grade,지식자산평가GR등급,기술평가TR등급,기업가치FV등급,보증심사등급,미래성장기업군,책임경영등급코드,(취급시)_당기_최종결산일자,(취급시)_당기_매출액,(취급시)_전기_매출액,(취급시)_당기_자산총계,(취급시)_전기_자산총계,(취급시)_당기_경상개발비,(취급시)_전기_경상개발비,(취급시)_당기_부채비율,(취급시)_전기_부채비율,(취급시)_당기_현금흐름등급,(취급시)_전기_현금흐름등급,부실사유발생일자,직접위탁부실발생금액_고객,부실여부,피보험자수_구분,지역구분,업력,부실기간,고객번호1,고객번호2,a,b,c,고객번호3,고객번호4
0,76691713,C32029,2013-12-24,소기업,부산 체육공원로,가구 제조업,NaN,1.00,1.00,1.00,NaN,NaN,TBF201813649,동래,2019-01-02,직접,운전자금,기업일반자금대출,30,90000000,0.00,45.00,NaN,NaN,1,일반심사(창업기업),1.00,미래상환능력 평가등급이 E등급 이하 (최근2개년 EBITDA이자보상배율이 계속 1미만),,,,,,,,,,2018-12-27,KRS-S,KR9,GR-6,NaN,NaN,K9,III군,NaN,2020-12-31,348.00,367.00,100.00,149.00,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,0,5인이하,부산,1835 days,NaT,076691713,076691713,07,669,1713,07-669-1713,07-669-1713
1,76553566,R91210,1987-04-11,소기업,경기 장흥면,두리랜드 운영,NaN,2.00,1.00,2.00,NaN,NaN,THS201912347,의정부,2019-01-02,직접,시설자금,각종시설자금대출,49,5000000000,0.00,50.00,NaN,1.00,1,NaN,3.00,당기 매출액대비 총차입금비율이 70% 초과,당기 매출액대비 운전자금차입금비율이 50% 초과,"기업가치가 ""0""이하인 기업 또는 기업가치평가등급이 ""FV-10""인 기업",,,,,,,,2018-11-05,KRS-C,KR9,GR-4,NaN,FV-10,K11,III군,NaN,2017-12-31,868.00,589.00,8606.00,6971.00,NaN,NaN,48.55,43.29,CR-5,CR-5,NaT,NaN,0,5인이하,경기,11589 days,NaT,076553566,076553566,07,655,3566,07-655-3566,07-655-3566
2,60895942,C20202,2002-04-23,소기업,경남 주촌면,합성수지,NaN,7.00,8.00,7.00,6.00,6.00,TQJ201813049,김해,2019-01-02,직접,운전자금,기업일반자금대출,4162,127500000,0.00,0.00,NaN,NaN,1,일반심사(비창업기업),1.00,"신청기업 최근 6개월 이내 주요국세(부가세,법인세,종합소득세) 체납",,,,,,,,,,2018-12-26,KRS-C,KR7,GR-4,NaN,NaN,K7,III군,NaN,2017-12-31,1333.00,2713.00,555.00,688.00,NaN,NaN,210.06,126.32,CR-3,NaN,NaT,NaN,0,10인이하,경남,6098 days,NaT,060895942,060895942,06,089,5942,06-089-5942,06-089-5942
3,76683394,G46103,2013-04-06,소기업,경기 내촌면,NaN,NaN,2.00,2.00,2.00,NaN,NaN,QAC201814191,마포,2019-01-02,직접,운전자금,기업일반자금대출,30,49500000,0.00,0.00,NaN,2.00,1,간이심사,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-12-27,ARS,AS9,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-31,196.00,NaN,35.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,0,5인이하,경기,2097 days,NaT,076683394,076683394,07,668,3394,07-668-3394,07-668-3394
4,76649561,C23221,2012-12-14,소기업,경기 조안면,NaN,NaN,4.00,3.00,4.00,NaN,NaN,TAP201813757,광진,2019-01-02,직접,운전자금,기업일반자금대출,30,45000000,0.00,0.00,NaN,2.00,1,간이심사,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-12-28,ARS,AS2,NaN,NaN,NaN,NaN,NaN,NaN,2019-12-31,312.00,217.00,505.00,254.00,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,0,5인이하,경기,2210 days,NaT,076649561,076649561,07,664,9561,07-664-9561,07-664-9561
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41192,79089943,C31114,2013-11-30,소기업,전라남도 삼호읍,NaN,NaN,6.00,6.00,NaN,NaN,NaN,TOG201912993,목포,2019-12-31,직접,운전자금,기업일반자금대출,1,100000000,0.00,30.00,3.00,3.00,1,간이심사,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-12-31,ARS,AS8,NaN,NaN,NaN,NaN,NaN,NaN,2018-12-31,2597.00,1205.00,318.00,188.00,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,0,10인이하,전라남도,2222 days,NaT,079089943,079089943,07,908,9943,07-908-9943,07-908-9943
41193,72587866,C26429,2011-08-06,소기업,경기도 수정구,ELS 소프트웨어개발외,NaN,50.00,50.00,33.00,21.00,14.00,QAF201912402,지식재산금융센터,2019-12-31,직접,운전자금,기업일반자금대출,1826,1600000000,0.00,0.00,4.00,4.00,1,혁신아이콘 Credit Line 건별심사,2.00,"기업가치가 ""0""이하인 기업 또는 기업가치평가등급이 ""FV-10""인 기업",보증심사등급이 'K15' (기타등급은 제외),,,,,,,,,2019-12-06,KRS-S,KR13,GR-3,NaN,FV-10,K15,IV군,NaN,2018-12-31,2753.00,789.00,13813.00,10439.00,257.00,75.00,71.06,28.91,CR-6,NaN,NaT,NaN,0,50인이하,경기도,3069 days,NaT,072587866,072587866,07,258,7866,07-258-7866,07-258-7866
41194,72587866,C26429,2011-08-06,소기업,경기도 수정구,ELS 소프트웨어개발외,NaN,50.00,50.00,33.00,21.00,14.00,QAF201912403,지식재산금융센터,2019-12-31,직접,운전자금,기업일반자금대출,1826,1600000000,0.00,0.00,4.00,5.00,1,혁신아이콘 Credit Line 건별심사,2.00,"기업가치가 ""0""이하인 기업 또는 기업가치평가등급이 ""FV-10""인 기업",보증심사등급이 'K15' (기타등급은 제외),,,,,,,,,2019-12-06,KRS-S,KR13,GR-3,NaN,FV-10,K15,IV군,NaN,2018-12-31,2753.00,789.00,13813.00,10439.00,257.00,75.00,71.06,28.91,CR-6,NaN,NaT,NaN,0,50인이하,경기도,3069 days,NaT,072587866,072587866,07,258,7866,07-258-7866,07-258-7866
41195,73645558,G47911,2011-09-29,중기업,서울특별시 테헤란로4길,화장품,NaN,95.00,95.00,77.00,62.00,73.00,QAF201912400,지식재산금융센터,2019-12-31,직접,운전자금,기업일반자금대출,1160,500000000,0.00,0.00,5.00,5.00,1,혁신아이콘 Credit Line 건별심사,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-30,KRS-S,KR6,GR-1,NaN,FV-5,K6,II군,NaN,2018-12-31,49956.00,37111.00,35556.00,17070.00,NaN,NaN,35.73,91.28,CR-5,NaN,NaT,NaN,0,50인초과,서울특별시,3015 days,NaT,073645558,073645558,07,364,5558,07-364-5558,07-364-5558
41196,73645558,G47911,2011-09-29,중기업,서울특별시 테헤란로4길,화장품,NaN,95.00,95.00,77.00,62.00,73.00,QAF201912401,지식재산금융센터,2019-12-31,직접,운전자금,기업일반자금대출,1160,500000000,0.00,0.00,5.00,4.00,1,혁신아이콘 Credit Line 건별심사,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-30,KRS-S,KR6,GR-1,NaN,FV-5,K6,II군,NaN,2018-12-31,49956.00,37111.00,35556.00,17070.00,NaN,NaN,35.73,91.28,CR-5,NaN,NaT,NaN,0,50인초과,서울특별시,3015 days,NaT,073645558,073645558,07,364,5558,07-364-5558,07-364-5558

5.2 주제별 부실현황

* 피벗테이블 생성을 위한 사용자 정의 함수

In [17]:
# 부실현황 파악을 위한 피벗데이블 생성 함수
def busil_rate(data, var):
    
    pivot = data.pivot_table(index=var, columns='부실여부', values='CNT', aggfunc=sum) # 피벗테이블 생성 
    pivot = pivot.fillna(0) # 결측값을 0으로 변경
    pivot['전체'] = pivot[1] + pivot[0]
    pivot['부실률'] = (pivot[1] / (pivot[0] + pivot[1]))*100  
    pivot.rename(columns={0:'정상',1:'부실'},inplace=True) # 변수 이름 변경
    pivot[['정상','부실','전체']] = pivot[['정상','부실','전체']].astype(int) # 표현형식을 정수형으로 변경
    pivot['부실률'] = pivot['부실률'].round(2) # 소수점 2자리에서 반올림
    globals()['pivot_{}'.format(var)] = pivot # 동적 변수 호출 (변수명을 동적으로 변경 : 어려운 문법)
    return

In [ ]:
* 사용자 정의 함수 적용 예시

In [18]:
busil_rate(base_data2,'자금용도')
pivot_자금용도

부실여부   정상  부실   전체  부실률
자금용도
시설자금   3637    68   3705    1.84
운전자금  36659   833  37492    2.22

In [19]:
busil_rate(base_data2,'기술평가TR등급')
pivot_기술평가TR등급

부실여부        정상  부실  전체  부실률
기술평가TR등급
TR-1              96     0    96    0.00
TR-2             324    11   335    3.28
TR-3             427     7   434    1.61
TR-4             611    23   634    3.63
TR-5             285     9   294    3.06
TR-6             238    14   252    5.56
TR-7              70     2    72    2.78
TR-8              79     2    81    2.47
TR-9               4     1     5   20.00

In [38]:
# 상품정보 개수별 부실현황
busil_rate(base_data2, '상품정보_자금특성개수')
pivot_상품정보_자금특성개수

부실여부                정상  부실   전체  부실률
상품정보_자금특성개수
1.00                   11675   245  11920    2.06
2.00                   12375   275  12650    2.17
3.00                    7806   187   7993    2.34
4.00                    3035    90   3125    2.88
5.00                     816    25    841    2.97
6.00                     155     3    158    1.90
7.00                      19     2     21    9.52
8.00                       2     0      2    0.00

In [20]:
busil_rate(base_data2,'grade')
pivot_grade

부실여부  정상  부실  전체  부실률
grade
AS1         53     0    53    0.00
AS10       916    31   947    3.27
AS11       492    16   508    3.15
AS12        65     1    66    1.52
AS13        32     1    33    3.03
AS14        16     0    16    0.00
AS15         1     0     1    0.00
AS2        120     0   120    0.00
AS3        196     1   197    0.51
AS4        295     2   297    0.67
AS5        427     5   432    1.16
AS6        507     4   511    0.78
AS7        671     9   680    1.32
AS8        908    17   925    1.84
AS9       1073    29  1102    2.63
F2          18     0    18    0.00
KR1          6     0     6    0.00
KR10      4836   182  5018    3.63
KR11      2426   143  2569    5.57
KR12       761    63   824    7.65
KR13       298    18   316    5.70
KR14       138    14   152    9.21
KR15        29    11    40   27.50
KR2         48     0    48    0.00
KR3        321     0   321    0.00
KR4       1179     3  1182    0.25
KR5       2359    10  2369    0.42
KR6       3867    11  3878    0.28
KR7       5025    75  5100    1.47
KR8       6188    93  6281    1.48
KR9       6735   153  6888    2.22

* 피벗테이블을 신용등급 순서로 정렬

In [21]:
# <신용등급별 정렬>

# 인덱스(신용등급)를 변수로 복사
pivot_grade['grade_list'] = pivot_grade.index  

# 신용등급 문자열 나누기
grade_head = pivot_grade['grade_list'].str[:2] 
grade_tail = pivot_grade['grade_list'].str[2:] 
grade_tail = pd.to_numeric(grade_tail) # 문자열을 숫자로 변경

# 신용등급별 정렬을 위한 변수 생성
pivot_grade['grade_head'] = grade_head 
pivot_grade['grade_tail'] = grade_tail
print(pivot_grade)

# 신용등급별 정렬
pivot_grade.sort_values(by=['grade_head', 'grade_tail'], ascending=[False, True], inplace=True)
pivot_grade.drop(['grade_list', 'grade_head', 'grade_tail'],axis=1) # 정렬을 위해 생성한 불필요한 변수 삭제

부실여부  정상  부실  전체  부실률 grade_list grade_head  grade_tail
grade
AS1         53     0    53    0.00        AS1         AS        1.00
AS10       916    31   947    3.27       AS10         AS       10.00
AS11       492    16   508    3.15       AS11         AS       11.00
AS12        65     1    66    1.52       AS12         AS       12.00
AS13        32     1    33    3.03       AS13         AS       13.00
AS14        16     0    16    0.00       AS14         AS       14.00
AS15         1     0     1    0.00       AS15         AS       15.00
AS2        120     0   120    0.00        AS2         AS        2.00
AS3        196     1   197    0.51        AS3         AS        3.00
AS4        295     2   297    0.67        AS4         AS        4.00
AS5        427     5   432    1.16        AS5         AS        5.00
AS6        507     4   511    0.78        AS6         AS        6.00
AS7        671     9   680    1.32        AS7         AS        7.00
AS8        908    17   925    1.84        AS8         AS        8.00
AS9       1073    29  1102    2.63        AS9         AS        9.00
F2          18     0    18    0.00         F2         F2         NaN
KR1          6     0     6    0.00        KR1         KR        1.00
KR10      4836   182  5018    3.63       KR10         KR       10.00
KR11      2426   143  2569    5.57       KR11         KR       11.00
KR12       761    63   824    7.65       KR12         KR       12.00
KR13       298    18   316    5.70       KR13         KR       13.00
KR14       138    14   152    9.21       KR14         KR       14.00
KR15        29    11    40   27.50       KR15         KR       15.00
KR2         48     0    48    0.00        KR2         KR        2.00
KR3        321     0   321    0.00        KR3         KR        3.00
KR4       1179     3  1182    0.25        KR4         KR        4.00
KR5       2359    10  2369    0.42        KR5         KR        5.00
KR6       3867    11  3878    0.28        KR6         KR        6.00
KR7       5025    75  5100    1.47        KR7         KR        7.00
KR8       6188    93  6281    1.48        KR8         KR        8.00
KR9       6735   153  6888    2.22        KR9         KR        9.00

부실여부  정상  부실  전체  부실률
grade
KR1          6     0     6    0.00
KR2         48     0    48    0.00
KR3        321     0   321    0.00
KR4       1179     3  1182    0.25
KR5       2359    10  2369    0.42
KR6       3867    11  3878    0.28
KR7       5025    75  5100    1.47
KR8       6188    93  6281    1.48
KR9       6735   153  6888    2.22
KR10      4836   182  5018    3.63
KR11      2426   143  2569    5.57
KR12       761    63   824    7.65
KR13       298    18   316    5.70
KR14       138    14   152    9.21
KR15        29    11    40   27.50
F2          18     0    18    0.00
AS1         53     0    53    0.00
AS2        120     0   120    0.00
AS3        196     1   197    0.51
AS4        295     2   297    0.67
AS5        427     5   432    1.16
AS6        507     4   511    0.78
AS7        671     9   680    1.32
AS8        908    17   925    1.84
AS9       1073    29  1102    2.63
AS10       916    31   947    3.27
AS11       492    16   508    3.15
AS12        65     1    66    1.52
AS13        32     1    33    3.03
AS14        16     0    16    0.00
AS15         1     0     1    0.00

* 그룹변수 생성 후 사용자 정의 함수 적용

In [22]:
# <변수별 범주 생성>
# 범주 기준값 정의
피보험자수_기준 = [
    base_data2['피보험자수_취급월'] <= 5,
    (base_data2['피보험자수_취급월'] > 5) & (base_data2['피보험자수_취급월'] <= 10),
    (base_data2['피보험자수_취급월'] > 10) & (base_data2['피보험자수_취급월'] <= 20),
    (base_data2['피보험자수_취급월'] > 20) & (base_data2['피보험자수_취급월'] <= 50),    
    (base_data2['피보험자수_취급월'] > 50)       
]
# 범주 이름 정의
피보험자수_그룹 = ['5인이하','10인이하','20인이하', '50인이하', '50인초과']

# 범주 생성
base_data2['피보험자수_구분'] = np.select(피보험자수_기준, 피보험자수_그룹)
base_data2

,고객번호,최종업종코드,설립일자,기업규모,사업장소재지,판매품목1,판매품목2,피보험자수_취급월,피보험자수_기준월,피보험자수_전년말,피보험자수_전전년말,피보험자수_전전전년말,원장번호,취급부점,보증취급일자,직위재구분,자금용도,주채무과목,순보증사용일수,신규증액금액,심사서상_기보보증잔액,심사서상_재단보증잔액,상품정보_기업특성개수,상품정보_자금특성개수,CNT,심사종류,심사체크리스트저촉건수,체크리스트저촉1,체크리스트저촉2,체크리스트저촉3,체크리스트저촉4,체크리스트저촉5,체크리스트저촉6,체크리스트저촉7,체크리스트저촉8,체크리스트저촉9,체크리스트저촉10,조사기준일자,평가모형,grade,지식자산평가GR등급,기술평가TR등급,기업가치FV등급,보증심사등급,미래성장기업군,책임경영등급코드,(취급시)_당기_최종결산일자,(취급시)_당기_매출액,(취급시)_전기_매출액,(취급시)_당기_자산총계,(취급시)_전기_자산총계,(취급시)_당기_경상개발비,(취급시)_전기_경상개발비,(취급시)_당기_부채비율,(취급시)_전기_부채비율,(취급시)_당기_현금흐름등급,(취급시)_전기_현금흐름등급,부실사유발생일자,직접위탁부실발생금액_고객,부실여부,피보험자수_구분
0,76691713,C32029,2013-12-24,소기업,부산 체육공원로,가구 제조업,NaN,1.00,1.00,1.00,NaN,NaN,TBF201813649,동래,2019-01-02,직접,운전자금,기업일반자금대출,30,90000000,0.00,45.00,NaN,NaN,1,일반심사(창업기업),1.00,미래상환능력 평가등급이 E등급 이하 (최근2개년 EBITDA이자보상배율이 계속 1미만),,,,,,,,,,2018-12-27,KRS-S,KR9,GR-6,NaN,NaN,K9,III군,NaN,2020-12-31,348.00,367.00,100.00,149.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,5인이하
1,76553566,R91210,1987-04-11,소기업,경기 장흥면,두리랜드 운영,NaN,2.00,1.00,2.00,NaN,NaN,THS201912347,의정부,2019-01-02,직접,시설자금,각종시설자금대출,49,5000000000,0.00,50.00,NaN,1.00,1,NaN,3.00,당기 매출액대비 총차입금비율이 70% 초과,당기 매출액대비 운전자금차입금비율이 50% 초과,"기업가치가 ""0""이하인 기업 또는 기업가치평가등급이 ""FV-10""인 기업",,,,,,,,2018-11-05,KRS-C,KR9,GR-4,NaN,FV-10,K11,III군,NaN,2017-12-31,868.00,589.00,8606.00,6971.00,NaN,NaN,48.55,43.29,CR-5,CR-5,NaN,NaN,0,5인이하
2,60895942,C20202,2002-04-23,소기업,경남 주촌면,합성수지,NaN,7.00,8.00,7.00,6.00,6.00,TQJ201813049,김해,2019-01-02,직접,운전자금,기업일반자금대출,4162,127500000,0.00,0.00,NaN,NaN,1,일반심사(비창업기업),1.00,"신청기업 최근 6개월 이내 주요국세(부가세,법인세,종합소득세) 체납",,,,,,,,,,2018-12-26,KRS-C,KR7,GR-4,NaN,NaN,K7,III군,NaN,2017-12-31,1333.00,2713.00,555.00,688.00,NaN,NaN,210.06,126.32,CR-3,NaN,NaN,NaN,0,10인이하
3,76683394,G46103,2013-04-06,소기업,경기 내촌면,NaN,NaN,2.00,2.00,2.00,NaN,NaN,QAC201814191,마포,2019-01-02,직접,운전자금,기업일반자금대출,30,49500000,0.00,0.00,NaN,2.00,1,간이심사,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-12-27,ARS,AS9,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-31,196.00,NaN,35.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,5인이하
4,76649561,C23221,2012-12-14,소기업,경기 조안면,NaN,NaN,4.00,3.00,4.00,NaN,NaN,TAP201813757,광진,2019-01-02,직접,운전자금,기업일반자금대출,30,45000000,0.00,0.00,NaN,2.00,1,간이심사,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-12-28,ARS,AS2,NaN,NaN,NaN,NaN,NaN,NaN,2019-12-31,312.00,217.00,505.00,254.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,5인이하
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41192,79089943,C31114,2013-11-30,소기업,전라남도 삼호읍,NaN,NaN,6.00,6.00,NaN,NaN,NaN,TOG201912993,목포,2019-12-31,직접,운전자금,기업일반자금대출,1,100000000,0.00,30.00,3.00,3.00,1,간이심사,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-12-31,ARS,AS8,NaN,NaN,NaN,NaN,NaN,NaN,2018-12-31,2597.00,1205.00,318.00,188.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,10인이하
41193,72587866,C26429,2011-08-06,소기업,경기도 수정구,ELS 소프트웨어개발외,NaN,50.00,50.00,33.00,21.00,14.00,QAF201912402,지식재산금융센터,2019-12-31,직접,운전자금,기업일반자금대출,1826,1600000000,0.00,0.00,4.00,4.00,1,혁신아이콘 Credit Line 건별심사,2.00,"기업가치가 ""0""이하인 기업 또는 기업가치평가등급이 ""FV-10""인 기업",보증심사등급이 'K15' (기타등급은 제외),,,,,,,,,2019-12-06,KRS-S,KR13,GR-3,NaN,FV-10,K15,IV군,NaN,2018-12-31,2753.00,789.00,13813.00,10439.00,257.00,75.00,71.06,28.91,CR-6,NaN,NaN,NaN,0,50인이하
41194,72587866,C26429,2011-08-06,소기업,경기도 수정구,ELS 소프트웨어개발외,NaN,50.00,50.00,33.00,21.00,14.00,QAF201912403,지식재산금융센터,2019-12-31,직접,운전자금,기업일반자금대출,1826,1600000000,0.00,0.00,4.00,5.00,1,혁신아이콘 Credit Line 건별심사,2.00,"기업가치가 ""0""이하인 기업 또는 기업가치평가등급이 ""FV-10""인 기업",보증심사등급이 'K15' (기타등급은 제외),,,,,,,,,2019-12-06,KRS-S,KR13,GR-3,NaN,FV-10,K15,IV군,NaN,2018-12-31,2753.00,789.00,13813.00,10439.00,257.00,75.00,71.06,28.91,CR-6,NaN,NaN,NaN,0,50인이하
41195,73645558,G47911,2011-09-29,중기업,서울특별시 테헤란로4길,화장품,NaN,95.00,95.00,77.00,62.00,73.00,QAF201912400,지식재산금융센터,2019-12-31,직접,운전자금,기업일반자금대출,1160,500000000,0.00,0.00,5.00,5.00,1,혁신아이콘 Credit Line 건별심사,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-30,KRS-S,KR6,GR-1,NaN,FV-5,K6,II군,NaN,2018-12-31,49956.00,37111.00,35556.00,17070.00,NaN,NaN,35.73,91.28,CR-5,NaN,NaN,NaN,0,50인초과
41196,73645558,G47911,2011-09-29,중기업,서울특별시 테헤란로4길,화장품,NaN,95.00,95.00,77.00,62.00,73.00,QAF201912401,지식재산금융센터,2019-12-31,직접,운전자금,기업일반자금대출,1160,500000000,0.00,0.00,5.00,4.00,1,혁신아이콘 Credit Line 건별심사,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-30,KRS-S,KR6,GR-1,NaN,FV-5,K6,II군,NaN,2018-12-31,49956.00,37111.00,35556.00,17070.00,NaN,NaN,35.73,91.28,CR-5,NaN,NaN,NaN,0,50인초과

In [23]:
busil_rate(base_data2,'피보험자수_구분')
pivot_피보험자수_구분

부실여부          정상  부실   전체  부실률
피보험자수_구분
0                   26     0     26    0.00
10인이하          6500   139   6639    2.09
20인이하          4179   110   4289    2.56
50인이하          2866    45   2911    1.55
50인초과          1402    10   1412    0.71
5인이하          25323   597  25920    2.30

5.3 품목별, 체크리스트별 부실

5.3.1 품목별 부실

In [39]:
# 품목별 부실

# 관심있는 품목 입력
products = ['자동차','엔진','밧데리']
product_list = '|'.join(products)

# 품목 테이블 생성
product_table = base_data2.loc[:,['판매품목1','판매품목2','부실여부','CNT']]
product_table[['판매품목1','판매품목2']] = product_table[['판매품목1','판매품목2']].fillna('')
product_table['판매품목'] = product_table['판매품목1'] + ' : ' + product_table['판매품목2']
product_table = product_table.drop(['판매품목1','판매품목2'] , axis=1)
product_table['특정품목'] = [ product_list if i is True else '00.기타' for i in product_table['판매품목'].str.contains(product_list)]
product_table.sort_values(by=['특정품목'], ascending=[False], inplace=True)
product_table

       부실여부  CNT               판매품목            특정품목
25138         0    1    자동차종합수리업 :   자동차|엔진|밧데리
32199         0    1          중고자동차 :   자동차|엔진|밧데리
29351         0    1          자동차부품 :   자동차|엔진|밧데리
29352         0    1    자동차 차체 부품 :   자동차|엔진|밧데리
32192         0    1      자동차부품제조 :   자동차|엔진|밧데리
...         ...  ...                    ...                 ...
14014         0    1       가스이음관 외 :              00.기타
14016         0    1  소방시설, 전기공사 :              00.기타
14017         0    1             잡화 외 :              00.기타
14018         0    1                     :              00.기타
41196         0    1              화장품 :              00.기타

[41197 rows x 4 columns]

In [40]:
# 품목별 부실현황
busil_rate(product_table, '특정품목')
pivot_특정품목

부실여부             정상  부실   전체  부실률
특정품목
00.기타             38802   865  39667    2.18
자동차|엔진|밧데리   1494    36   1530    2.35

5.3.2 체크리스트별 부실

* 체크리스트 변수 탐색

In [32]:
# 부실이 많이 발생하는 체크리스트 탐색
busil_rate(base_data2, '심사체크리스트저촉건수')
pivot_심사체크리스트저촉건수

부실여부                정상  부실  전체  부실률
심사체크리스트저촉건수
1.00                    6576   199  6775    2.94
2.00                    1999    43  2042    2.11
3.00                     429    21   450    4.67
4.00                      78     6    84    7.14
5.00                      34     1    35    2.86
6.00                      15    14    29   48.28
7.00                       5     1     6   16.67
9.00                       1     0     1    0.00
12.00                      0     4     4  100.00

In [33]:
print(base_data2['체크리스트저촉1'].value_counts())
print(base_data2['체크리스트저촉10'].value_counts())

미래상환능력 평가등급이 E등급 이하 (최근2개년 EBITDA이자보상배율이 계속 1미만)     2081
총차입금이 당기 매출액 초과                                                        1936
신청기업 최근 6개월 이내 주요국세(부가세,법인세,종합소득세) 체납                   1919
최근 1년 이내 대표자 또는 실제경영자 변경                                           965
당기 매출액대비 총차입금비율이 70% 초과                                             939
전기대비 당기매출액이 25%이상 감소                                                  277
대표자(실제경영자)의 동업계 종사경험이 1년 미만                                     212
사업장 또는 거주주택에 대한 권리침해                                                197
최근 2개년 EBITDA 이자보상배율이 계속 1미만                                         160
당기 매출액대비 운전자금차입금비율이 50% 초과                                       153
자기자본대비 총차입금 비율이 400% 초과                                              138
자기자본 전액잠식                                                                    92
신용보증부실(기보, 재단, SOC기금, 부실유보기업 포함)                                 73
"한국신용정보원의 신용정보관리규약"에  따른 신보의 "신용관리등급" 보유               60
최근 3개월이내 10일 이상 계속된 연체대출금(연체중 포함) 보유                         57
기업가치가 "0"이하인 기업 또는 기업가치평가등급이 "FV-10"인 기업                     35
본건 금융성 운전자금보증 신청금액이 기업가치 초과                                    29
업종별 부채비율상한선 초과                                                           24
보증심사등급이 K12~K14등급이고, 현금흐름표 종합판정등급이 'CR-5' 이하                19
국세 또는 지방세 체납                                                                13
심사기준일 현재 대표자CB등급(실제경영자 포함)이 CBR-6 이하인 기업                    12
심사기준일 현재“(CB)연체 및 보험료 체납정보”보유                                     12
SESS등급이 “S5”등급인 기업 또는 SBSS등급이 “SB9" 등급 이하인 기업                     7
지식자산평가등급 "GR-10" 이거나 기술자산평가등급 "TR-10"인 기업                       4
심사기준일 현재 신청기업 또는 대표자(실제경영자 포함)가 (CB)연체정보 보유             2
당좌부도 발생                                                                         2
전기대비 당기매출액이 30%이상 감소                                                    2
심사기준일 현재 자가사업장 보유 또는 임차사업장에 입주하였을 것                       2
창업기업평가등급(SBSS)이 “SB9” 등급이하인 기업                                        1
보증심사등급이 "K15"등급 이하(기타등급 제외)인 기업 또는 “SB9" 등급 이하인 기업       1
최근 3개월이내 10일 이상 계속된 연체대출금(연체중 포함)이 없을 것                     1
창업준비 단계 심사 당시 업종과 창업기업 영위 업종이 동일할 것                         1
Name: 체크리스트저촉1, dtype: int64

* 체크리스트를 정리하는 함수 생성

In [35]:
# 체크리스트 병합 초기 테이블 생성
check_table = base_data2.loc[:,['체크리스트저촉1','부실여부','CNT']]
check_table.rename(columns={'체크리스트저촉1':'체크리스트저촉'}, inplace=True)
del_idx = check_table[check_table['체크리스트저촉']==' '].index
check_table = check_table.drop(del_idx)
check_table = check_table.dropna()
check_table.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9426 entries, 0 to 41194
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   체크리스트저촉  9426 non-null   object
 1   부실여부     9426 non-null   int64
 2   CNT      9426 non-null   int64
dtypes: int64(2), object(1)
memory usage: 294.6+ KB

In [36]:
# 체크리스트 병합 함수
def check_concat(table, var):
    global check_table
    # 칼럼 선택
    check_table_tmp = base_data2.loc[:,[var,'부실여부','CNT']]
    # 변수이름 변경 : 통일화
    check_table_tmp.rename(columns={var:'체크리스트저촉'}, inplace=True)
    # 삭제대상 인덱스 정의 : 공백만 있는 row 삭제
    del_idx = check_table_tmp[check_table_tmp['체크리스트저촉']==' '].index
    # 행삭제
    check_table_tmp = check_table_tmp.drop(del_idx)
    # 결측값 삭제
    check_table_tmp = check_table_tmp.dropna()
    # 데이터 병합
    check_table = pd.concat([table, check_table_tmp])
    print(check_table.info())
    return check_table

In [34]:
# 체크리스트 병합 
check_concat(check_table, '체크리스트저촉2')
check_concat(check_table, '체크리스트저촉3')
check_concat(check_table, '체크리스트저촉4')
check_concat(check_table, '체크리스트저촉5')
check_concat(check_table, '체크리스트저촉6')
check_concat(check_table, '체크리스트저촉7')
check_concat(check_table, '체크리스트저촉8')
check_concat(check_table, '체크리스트저촉9')
check_concat(check_table, '체크리스트저촉10')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12077 entries, 0 to 41194
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   체크리스트저촉  12077 non-null  object
 1   부실여부     12077 non-null  int64
 2   CNT      12077 non-null  int64
dtypes: int64(2), object(1)
memory usage: 377.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 12686 entries, 0 to 41188
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   체크리스트저촉  12686 non-null  object
 1   부실여부     12686 non-null  int64
 2   CNT      12686 non-null  int64
dtypes: int64(2), object(1)
memory usage: 396.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 12845 entries, 0 to 41140
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   체크리스트저촉  12845 non-null  object
 1   부실여부     12845 non-null  int64
 2   CNT      12845 non-null  int64
dtypes: int64(2), object(1)
memory usage: 401.4+ KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 12920 entries, 0 to 41096
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   체크리스트저촉  12920 non-null  object
 1   부실여부     12920 non-null  int64
 2   CNT      12920 non-null  int64
dtypes: int64(2), object(1)
memory usage: 403.8+ KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 12960 entries, 0 to 40864
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   체크리스트저촉  12960 non-null  object
 1   부실여부     12960 non-null  int64
 2   CNT      12960 non-null  int64
dtypes: int64(2), object(1)
memory usage: 405.0+ KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 12971 entries, 0 to 37186
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   체크리스트저촉  12971 non-null  object
 1   부실여부     12971 non-null  int64
 2   CNT      12971 non-null  int64
dtypes: int64(2), object(1)
memory usage: 405.3+ KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 12976 entries, 0 to 25003
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   체크리스트저촉  12976 non-null  object
 1   부실여부     12976 non-null  int64
 2   CNT      12976 non-null  int64
dtypes: int64(2), object(1)
memory usage: 405.5+ KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 12981 entries, 0 to 25003
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   체크리스트저촉  12981 non-null  object
 1   부실여부     12981 non-null  int64
 2   CNT      12981 non-null  int64
dtypes: int64(2), object(1)
memory usage: 405.7+ KB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 12985 entries, 0 to 25003
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   체크리스트저촉  12985 non-null  object
 1   부실여부     12985 non-null  int64
 2   CNT      12985 non-null  int64
dtypes: int64(2), object(1)
memory usage: 405.8+ KB
None

,체크리스트저촉,부실여부,CNT
0,미래상환능력 평가등급이 E등급 이하 (최근2개년 EBITDA이자보상배율이 계속 1미만),0,1
1,당기 매출액대비 총차입금비율이 70% 초과,0,1
2,"신청기업 최근 6개월 이내 주요국세(부가세,법인세,종합소득세) 체납",0,1
12,총차입금이 당기 매출액 초과,0,1
13,"신청기업 최근 6개월 이내 주요국세(부가세,법인세,종합소득세) 체납",0,1
...,...,...,...
25003,"보증심사등급이 K12~K14등급이고, 현금흐름표 종합판정등급이 'CR-5' 이하",1,1
24650,심사기준일 현재 대표자CB등급(실제경영자 포함)이 CBR-6 이하인 기업,1,1
24651,심사기준일 현재 대표자CB등급(실제경영자 포함)이 CBR-6 이하인 기업,1,1
25002,심사기준일 현재 대표자CB등급(실제경영자 포함)이 CBR-6 이하인 기업,1,1
25003,심사기준일 현재 대표자CB등급(실제경영자 포함)이 CBR-6 이하인 기업,1,1

In [37]:
# 체크리스트 부실현황
busil_rate(check_table, '체크리스트저촉')
pivot_체크리스트저촉.sort_values(by=['부실률'], ascending=False, inplace=True)
pivot_체크리스트저촉

부실여부,정상,부실,전체,부실률
체크리스트저촉,,,,
심사기준일 현재“(CB)연체 및 보험료 체납정보”보유,8,4,12,33.33
국세 또는 지방세 체납,9,4,13,30.77
"지식자산평가등급 ""GR-10"" 이거나 기술자산평가등급 ""TR-10""인 기업",3,1,4,25.00
심사기준일 현재 대표자CB등급(실제경영자 포함)이 CBR-6 이하인 기업,9,3,12,25.00
최근 3개월이내 10일 이상 계속된 연체대출금(연체중 포함) 보유,46,11,57,19.30
"보증심사등급이 K12~K14등급이고, 현금흐름표 종합판정등급이 'CR-5' 이하",16,3,19,15.79
"""한국신용정보원의 신용정보관리규약""에 따른 신보의 ""신용관리등급"" 보유",51,9,60,15.00
"신용보증부실(기보, 재단, SOC기금, 부실유보기업 포함)",66,7,73,9.59
사업장 또는 거주주택에 대한 권리침해,182,15,197,7.61
대표자(실제경영자)의 동업계 종사경험이 1년 미만,201,11,212,5.19
"신청기업 최근 6개월 이내 주요국세(부가세,법인세,종합소득세) 체납",1848,71,1919,3.70
미래상환능력 평가등급이 E등급 이하 (최근2개년 EBITDA이자보상배율이 계속 1미만),2008,73,2081,3.51
최근 1년 이내 대표자 또는 실제경영자 변경,944,21,965,2.18
자기자본 전액잠식,90,2,92,2.17
총차입금이 당기 매출액 초과,1903,33,1936,1.70
당기 매출액대비 총차입금비율이 70% 초과,924,15,939,1.60
자기자본대비 총차입금 비율이 400% 초과,136,2,138,1.45
당기 매출액대비 운전자금차입금비율이 50% 초과,151,2,153,1.31
전기대비 당기매출액이 25%이상 감소,275,2,277,0.72
전기대비 당기매출액이 30%이상 감소,2,0,2,0.00
창업준비 단계 심사 당시 업종과 창업기업 영위 업종이 동일할 것,1,0,1,0.00
창업기업평가등급(SBSS)이 “SB9” 등급이하인 기업,1,0,1,0.00
최근 2개년 EBITDA 이자보상배율이 계속 1미만,160,0,160,0.00
심사기준일 현재 신청기업 또는 대표자(실제경영자 포함)가 (CB)연체정보 보유,2,0,2,0.00
업종별 부채비율상한선 초과,24,0,24,0.00
심사기준일 현재 자가사업장 보유 또는 임차사업장에 입주하였을 것,2,0,2,0.00
"SESS등급이 “S5”등급인 기업 또는 SBSS등급이 “SB9"" 등급 이하인 기업",7,0,7,0.00
본건 금융성 운전자금보증 신청금액이 기업가치 초과,29,0,29,0.00
"보증심사등급이 ""K15""등급 이하(기타등급 제외)인 기업 또는 “SB9"" 등급 이하인 기업",1,0,1,0.00
당좌부도 발생,2,0,2,0.00
"기업가치가 ""0""이하인 기업 또는 기업가치평가등급이 ""FV-10""인 기업",35,0,35,0.00
최근 3개월이내 10일 이상 계속된 연체대출금(연체중 포함)이 없을 것,1,0,1,0.00

5.3.3 품목별 부실현황 2 (제외품목 포함)

In [41]:
# 관심있는 품목 입력
products = ['자동차','엔진','밧데리']
product_list = '|'.join(products)

# 제외할 품목 입력
products_exclude = ['중고자동차']
product_exclude_list = '|'.join(products_exclude)

# 품목 테이블 생성 (제외 품목 반영)
product_table_ex = base_data2.loc[:,['판매품목1','판매품목2','부실여부','CNT']]
product_table_ex[['판매품목1','판매품목2']] = product_table_ex[['판매품목1','판매품목2']].fillna('')
product_table_ex['판매품목'] = product_table_ex['판매품목1'] + ' : ' + product_table_ex['판매품목2']
product_table_ex = product_table_ex.drop(['판매품목1','판매품목2'] , axis=1)
product_table_ex['특정품목'] = [ product_list if i is True else '00.기타' for i in (product_table_ex['판매품목'].str.contains(product_list))
                            & (product_table_ex['판매품목'].str.contains(product_exclude_list)== False)]
product_table_ex.sort_values(by=['특정품목'], ascending=[False], inplace=True)
product_table_ex

       부실여부  CNT                             판매품목            특정품목
35614         0    1                        자동차부품 :   자동차|엔진|밧데리
22485         0    1                       자동차 부품 :   자동차|엔진|밧데리
1751          0    1                       중고 자동차 :   자동차|엔진|밧데리
32182         0    1                    자동차용접지그 :   자동차|엔진|밧데리
32176         0    1  (주)현대자동차 : 자동차 정비 서비스  자동차|엔진|밧데리
...         ...  ...                                  ...                 ...
13992         0    1                              족발 :              00.기타
13993         1    1                         주유소 등 :              00.기타
13994         1    1                         주유소 등 :              00.기타
13995         0    1                의료기기 및 소모품 :              00.기타
41196         0    1                            화장품 :              00.기타

[41197 rows x 4 columns]

In [42]:
# 품목별 부실현황 (제외품목 포함)
busil_rate(product_table_ex, '특정품목')
pivot_특정품목

부실여부             정상  부실   전체  부실률
특정품목
00.기타             38911   872  39783    2.19
자동차|엔진|밧데리   1385    29   1414    2.05

5.3.4 문자열 테크닉

* 수도권 부실현황 : 문자열 나누기

In [24]:
# <텍스트 나누기 (공백 기준)>

# 사업장 소재지 별 광역 행정단위 추출
split_area = base_data2['사업장소재지'].str.split(" ")
base_data2['지역구분'] = split_area.str.get(0) # 텍스트 나누기 중 첫번째 값 선택
base_data2

,고객번호,최종업종코드,설립일자,기업규모,사업장소재지,판매품목1,판매품목2,피보험자수_취급월,피보험자수_기준월,피보험자수_전년말,피보험자수_전전년말,피보험자수_전전전년말,원장번호,취급부점,보증취급일자,직위재구분,자금용도,주채무과목,순보증사용일수,신규증액금액,심사서상_기보보증잔액,심사서상_재단보증잔액,상품정보_기업특성개수,상품정보_자금특성개수,CNT,심사종류,심사체크리스트저촉건수,체크리스트저촉1,체크리스트저촉2,체크리스트저촉3,체크리스트저촉4,체크리스트저촉5,체크리스트저촉6,체크리스트저촉7,체크리스트저촉8,체크리스트저촉9,체크리스트저촉10,조사기준일자,평가모형,grade,지식자산평가GR등급,기술평가TR등급,기업가치FV등급,보증심사등급,미래성장기업군,책임경영등급코드,(취급시)_당기_최종결산일자,(취급시)_당기_매출액,(취급시)_전기_매출액,(취급시)_당기_자산총계,(취급시)_전기_자산총계,(취급시)_당기_경상개발비,(취급시)_전기_경상개발비,(취급시)_당기_부채비율,(취급시)_전기_부채비율,(취급시)_당기_현금흐름등급,(취급시)_전기_현금흐름등급,부실사유발생일자,직접위탁부실발생금액_고객,부실여부,피보험자수_구분,지역구분
0,76691713,C32029,2013-12-24,소기업,부산 체육공원로,가구 제조업,NaN,1.00,1.00,1.00,NaN,NaN,TBF201813649,동래,2019-01-02,직접,운전자금,기업일반자금대출,30,90000000,0.00,45.00,NaN,NaN,1,일반심사(창업기업),1.00,미래상환능력 평가등급이 E등급 이하 (최근2개년 EBITDA이자보상배율이 계속 1미만),,,,,,,,,,2018-12-27,KRS-S,KR9,GR-6,NaN,NaN,K9,III군,NaN,2020-12-31,348.00,367.00,100.00,149.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,5인이하,부산
1,76553566,R91210,1987-04-11,소기업,경기 장흥면,두리랜드 운영,NaN,2.00,1.00,2.00,NaN,NaN,THS201912347,의정부,2019-01-02,직접,시설자금,각종시설자금대출,49,5000000000,0.00,50.00,NaN,1.00,1,NaN,3.00,당기 매출액대비 총차입금비율이 70% 초과,당기 매출액대비 운전자금차입금비율이 50% 초과,"기업가치가 ""0""이하인 기업 또는 기업가치평가등급이 ""FV-10""인 기업",,,,,,,,2018-11-05,KRS-C,KR9,GR-4,NaN,FV-10,K11,III군,NaN,2017-12-31,868.00,589.00,8606.00,6971.00,NaN,NaN,48.55,43.29,CR-5,CR-5,NaN,NaN,0,5인이하,경기
2,60895942,C20202,2002-04-23,소기업,경남 주촌면,합성수지,NaN,7.00,8.00,7.00,6.00,6.00,TQJ201813049,김해,2019-01-02,직접,운전자금,기업일반자금대출,4162,127500000,0.00,0.00,NaN,NaN,1,일반심사(비창업기업),1.00,"신청기업 최근 6개월 이내 주요국세(부가세,법인세,종합소득세) 체납",,,,,,,,,,2018-12-26,KRS-C,KR7,GR-4,NaN,NaN,K7,III군,NaN,2017-12-31,1333.00,2713.00,555.00,688.00,NaN,NaN,210.06,126.32,CR-3,NaN,NaN,NaN,0,10인이하,경남
3,76683394,G46103,2013-04-06,소기업,경기 내촌면,NaN,NaN,2.00,2.00,2.00,NaN,NaN,QAC201814191,마포,2019-01-02,직접,운전자금,기업일반자금대출,30,49500000,0.00,0.00,NaN,2.00,1,간이심사,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-12-27,ARS,AS9,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-31,196.00,NaN,35.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,5인이하,경기
4,76649561,C23221,2012-12-14,소기업,경기 조안면,NaN,NaN,4.00,3.00,4.00,NaN,NaN,TAP201813757,광진,2019-01-02,직접,운전자금,기업일반자금대출,30,45000000,0.00,0.00,NaN,2.00,1,간이심사,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-12-28,ARS,AS2,NaN,NaN,NaN,NaN,NaN,NaN,2019-12-31,312.00,217.00,505.00,254.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,5인이하,경기
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41192,79089943,C31114,2013-11-30,소기업,전라남도 삼호읍,NaN,NaN,6.00,6.00,NaN,NaN,NaN,TOG201912993,목포,2019-12-31,직접,운전자금,기업일반자금대출,1,100000000,0.00,30.00,3.00,3.00,1,간이심사,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-12-31,ARS,AS8,NaN,NaN,NaN,NaN,NaN,NaN,2018-12-31,2597.00,1205.00,318.00,188.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,10인이하,전라남도
41193,72587866,C26429,2011-08-06,소기업,경기도 수정구,ELS 소프트웨어개발외,NaN,50.00,50.00,33.00,21.00,14.00,QAF201912402,지식재산금융센터,2019-12-31,직접,운전자금,기업일반자금대출,1826,1600000000,0.00,0.00,4.00,4.00,1,혁신아이콘 Credit Line 건별심사,2.00,"기업가치가 ""0""이하인 기업 또는 기업가치평가등급이 ""FV-10""인 기업",보증심사등급이 'K15' (기타등급은 제외),,,,,,,,,2019-12-06,KRS-S,KR13,GR-3,NaN,FV-10,K15,IV군,NaN,2018-12-31,2753.00,789.00,13813.00,10439.00,257.00,75.00,71.06,28.91,CR-6,NaN,NaN,NaN,0,50인이하,경기도
41194,72587866,C26429,2011-08-06,소기업,경기도 수정구,ELS 소프트웨어개발외,NaN,50.00,50.00,33.00,21.00,14.00,QAF201912403,지식재산금융센터,2019-12-31,직접,운전자금,기업일반자금대출,1826,1600000000,0.00,0.00,4.00,5.00,1,혁신아이콘 Credit Line 건별심사,2.00,"기업가치가 ""0""이하인 기업 또는 기업가치평가등급이 ""FV-10""인 기업",보증심사등급이 'K15' (기타등급은 제외),,,,,,,,,2019-12-06,KRS-S,KR13,GR-3,NaN,FV-10,K15,IV군,NaN,2018-12-31,2753.00,789.00,13813.00,10439.00,257.00,75.00,71.06,28.91,CR-6,NaN,NaN,NaN,0,50인이하,경기도
41195,73645558,G47911,2011-09-29,중기업,서울특별시 테헤란로4길,화장품,NaN,95.00,95.00,77.00,62.00,73.00,QAF201912400,지식재산금융센터,2019-12-31,직접,운전자금,기업일반자금대출,1160,500000000,0.00,0.00,5.00,5.00,1,혁신아이콘 Credit Line 건별심사,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-30,KRS-S,KR6,GR-1,NaN,FV-5,K6,II군,NaN,2018-12-31,49956.00,37111.00,35556.00,17070.00,NaN,NaN,35.73,91.28,CR-5,NaN,NaN,NaN,0,50인초과,서울특별시
41196,73645558,G47911,2011-09-29,중기업,서울특별시 테헤란로4길,화장품,NaN,95.00,95.00,77.00,62.00,73.00,QAF201912401,지식재산금융센터,2019-12-31,직접,운전자금,기업일반자금대출,1160,500000000,0.00,0.00,5.00,4.00,1,혁신아이콘 Credit Line 건별심사,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-30,KRS-S,KR6,GR-1,NaN,FV-5,K6,II군,NaN,2018-12-31,49956.00,37111.00,35556.00,17070.00,NaN,NaN,35.73,91.28,CR-5,NaN,NaN,NaN,0,50인초과,서울특별시

In [30]:
# 수도권 리스트
city_area = ['서울','경기','인천']
base_data2['수도권여부'] = ['수도권' if i in city_area else '비수도권' for i in base_data2['지역구분']]

In [25]:
# 지역구분별 부실
busil_rate(base_data2,'지역구분')
pivot_지역구분

부실여부        정상  부실  전체  부실률
지역구분
강원             282     5   287    1.74
강원도           597    16   613    2.61
경기            3339    78  3417    2.28
경기도          7899   152  8051    1.89
경남            1004    45  1049    4.29
경북             777    16   793    2.02
경상남도        1684    49  1733    2.83
경상북도        1422    44  1466    3.00
광주             238     5   243    2.06
광주광역시       721     8   729    1.10
대구             624     8   632    1.27
대구광역시      1320    39  1359    2.87
대전             261     6   267    2.25
대전광역시       654     7   661    1.06
부산            1034    15  1049    1.43
부산광역시      2075    41  2116    1.94
부산시             1     0     1    0.00
서울            2148    55  2203    2.50
서울시             3     0     3    0.00
서울특별시      6072   142  6214    2.29
세종              32     1    33    3.03
세종특별자치시   116     4   120    3.33
울산             260     3   263    1.14
울산광역시       431    10   441    2.27
울산시             1     0     1    0.00
인천             568     9   577    1.56
인천광역시      1488    38  1526    2.49
전남             364    12   376    3.19
전라남도         756    15   771    1.95
전라북도         850    15   865    1.73
전북             387     5   392    1.28
제주             139     3   142    2.11
제주특별자치도   360     8   368    2.17
충남             465    12   477    2.52
충북             338     9   347    2.59
충청남도         801    15   816    1.84
충청북도         785    11   796    1.38

* 고객번호 핸들링 : 문자열 형태 변화

In [29]:
# <문자열 형태 변환>

# 빈 자리수 0으로 채우기 1 : zfill()
base_data2['고객번호1'] = base_data2['고객번호'].astype(str) # 숫자변수를 문자열 변수로 전환
base_data2['고객번호1'] = base_data2['고객번호1'].str.zfill(width=9) # 9자리 중 빈 자리를 0으로 채움

# 고객번호 슬라이싱 후 변수 생성
a=base_data2['고객번호1'].str[:2]
b=base_data2['고객번호1'].str[2:5]
c=base_data2['고객번호1'].str[5:9]

# - 로 연결하기 1 : + 기호 사용
base_data2['고객번호2'] = a + '-' + b + '-' + c

base_data2

,고객번호,최종업종코드,설립일자,기업규모,사업장소재지,판매품목1,판매품목2,피보험자수_취급월,피보험자수_기준월,피보험자수_전년말,피보험자수_전전년말,피보험자수_전전전년말,원장번호,취급부점,보증취급일자,직위재구분,자금용도,주채무과목,순보증사용일수,신규증액금액,심사서상_기보보증잔액,심사서상_재단보증잔액,상품정보_기업특성개수,상품정보_자금특성개수,CNT,심사종류,심사체크리스트저촉건수,체크리스트저촉1,체크리스트저촉2,체크리스트저촉3,체크리스트저촉4,체크리스트저촉5,체크리스트저촉6,체크리스트저촉7,체크리스트저촉8,체크리스트저촉9,체크리스트저촉10,조사기준일자,평가모형,grade,지식자산평가GR등급,기술평가TR등급,기업가치FV등급,보증심사등급,미래성장기업군,책임경영등급코드,(취급시)_당기_최종결산일자,(취급시)_당기_매출액,(취급시)_전기_매출액,(취급시)_당기_자산총계,(취급시)_전기_자산총계,(취급시)_당기_경상개발비,(취급시)_전기_경상개발비,(취급시)_당기_부채비율,(취급시)_전기_부채비율,(취급시)_당기_현금흐름등급,(취급시)_전기_현금흐름등급,부실사유발생일자,직접위탁부실발생금액_고객,부실여부,피보험자수_구분,지역구분,업력,부실기간,고객번호1,고객번호2,a,b,c,고객번호3,고객번호4
0,76691713,C32029,2013-12-24,소기업,부산 체육공원로,가구 제조업,NaN,1.00,1.00,1.00,NaN,NaN,TBF201813649,동래,2019-01-02,직접,운전자금,기업일반자금대출,30,90000000,0.00,45.00,NaN,NaN,1,일반심사(창업기업),1.00,미래상환능력 평가등급이 E등급 이하 (최근2개년 EBITDA이자보상배율이 계속 1미만),,,,,,,,,,2018-12-27,KRS-S,KR9,GR-6,NaN,NaN,K9,III군,NaN,2020-12-31,348.00,367.00,100.00,149.00,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,0,5인이하,부산,1835 days,NaT,076691713,07-669-1713,07,669,1713,07-669-1713,07-669-1713
1,76553566,R91210,1987-04-11,소기업,경기 장흥면,두리랜드 운영,NaN,2.00,1.00,2.00,NaN,NaN,THS201912347,의정부,2019-01-02,직접,시설자금,각종시설자금대출,49,5000000000,0.00,50.00,NaN,1.00,1,NaN,3.00,당기 매출액대비 총차입금비율이 70% 초과,당기 매출액대비 운전자금차입금비율이 50% 초과,"기업가치가 ""0""이하인 기업 또는 기업가치평가등급이 ""FV-10""인 기업",,,,,,,,2018-11-05,KRS-C,KR9,GR-4,NaN,FV-10,K11,III군,NaN,2017-12-31,868.00,589.00,8606.00,6971.00,NaN,NaN,48.55,43.29,CR-5,CR-5,NaT,NaN,0,5인이하,경기,11589 days,NaT,076553566,07-655-3566,07,655,3566,07-655-3566,07-655-3566
2,60895942,C20202,2002-04-23,소기업,경남 주촌면,합성수지,NaN,7.00,8.00,7.00,6.00,6.00,TQJ201813049,김해,2019-01-02,직접,운전자금,기업일반자금대출,4162,127500000,0.00,0.00,NaN,NaN,1,일반심사(비창업기업),1.00,"신청기업 최근 6개월 이내 주요국세(부가세,법인세,종합소득세) 체납",,,,,,,,,,2018-12-26,KRS-C,KR7,GR-4,NaN,NaN,K7,III군,NaN,2017-12-31,1333.00,2713.00,555.00,688.00,NaN,NaN,210.06,126.32,CR-3,NaN,NaT,NaN,0,10인이하,경남,6098 days,NaT,060895942,06-089-5942,06,089,5942,06-089-5942,06-089-5942
3,76683394,G46103,2013-04-06,소기업,경기 내촌면,NaN,NaN,2.00,2.00,2.00,NaN,NaN,QAC201814191,마포,2019-01-02,직접,운전자금,기업일반자금대출,30,49500000,0.00,0.00,NaN,2.00,1,간이심사,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-12-27,ARS,AS9,NaN,NaN,NaN,NaN,NaN,NaN,2017-12-31,196.00,NaN,35.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,0,5인이하,경기,2097 days,NaT,076683394,07-668-3394,07,668,3394,07-668-3394,07-668-3394
4,76649561,C23221,2012-12-14,소기업,경기 조안면,NaN,NaN,4.00,3.00,4.00,NaN,NaN,TAP201813757,광진,2019-01-02,직접,운전자금,기업일반자금대출,30,45000000,0.00,0.00,NaN,2.00,1,간이심사,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2018-12-28,ARS,AS2,NaN,NaN,NaN,NaN,NaN,NaN,2019-12-31,312.00,217.00,505.00,254.00,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,0,5인이하,경기,2210 days,NaT,076649561,07-664-9561,07,664,9561,07-664-9561,07-664-9561
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41192,79089943,C31114,2013-11-30,소기업,전라남도 삼호읍,NaN,NaN,6.00,6.00,NaN,NaN,NaN,TOG201912993,목포,2019-12-31,직접,운전자금,기업일반자금대출,1,100000000,0.00,30.00,3.00,3.00,1,간이심사,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-12-31,ARS,AS8,NaN,NaN,NaN,NaN,NaN,NaN,2018-12-31,2597.00,1205.00,318.00,188.00,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,0,10인이하,전라남도,2222 days,NaT,079089943,07-908-9943,07,908,9943,07-908-9943,07-908-9943
41193,72587866,C26429,2011-08-06,소기업,경기도 수정구,ELS 소프트웨어개발외,NaN,50.00,50.00,33.00,21.00,14.00,QAF201912402,지식재산금융센터,2019-12-31,직접,운전자금,기업일반자금대출,1826,1600000000,0.00,0.00,4.00,4.00,1,혁신아이콘 Credit Line 건별심사,2.00,"기업가치가 ""0""이하인 기업 또는 기업가치평가등급이 ""FV-10""인 기업",보증심사등급이 'K15' (기타등급은 제외),,,,,,,,,2019-12-06,KRS-S,KR13,GR-3,NaN,FV-10,K15,IV군,NaN,2018-12-31,2753.00,789.00,13813.00,10439.00,257.00,75.00,71.06,28.91,CR-6,NaN,NaT,NaN,0,50인이하,경기도,3069 days,NaT,072587866,07-258-7866,07,258,7866,07-258-7866,07-258-7866
41194,72587866,C26429,2011-08-06,소기업,경기도 수정구,ELS 소프트웨어개발외,NaN,50.00,50.00,33.00,21.00,14.00,QAF201912403,지식재산금융센터,2019-12-31,직접,운전자금,기업일반자금대출,1826,1600000000,0.00,0.00,4.00,5.00,1,혁신아이콘 Credit Line 건별심사,2.00,"기업가치가 ""0""이하인 기업 또는 기업가치평가등급이 ""FV-10""인 기업",보증심사등급이 'K15' (기타등급은 제외),,,,,,,,,2019-12-06,KRS-S,KR13,GR-3,NaN,FV-10,K15,IV군,NaN,2018-12-31,2753.00,789.00,13813.00,10439.00,257.00,75.00,71.06,28.91,CR-6,NaN,NaT,NaN,0,50인이하,경기도,3069 days,NaT,072587866,07-258-7866,07,258,7866,07-258-7866,07-258-7866
41195,73645558,G47911,2011-09-29,중기업,서울특별시 테헤란로4길,화장품,NaN,95.00,95.00,77.00,62.00,73.00,QAF201912400,지식재산금융센터,2019-12-31,직접,운전자금,기업일반자금대출,1160,500000000,0.00,0.00,5.00,5.00,1,혁신아이콘 Credit Line 건별심사,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-30,KRS-S,KR6,GR-1,NaN,FV-5,K6,II군,NaN,2018-12-31,49956.00,37111.00,35556.00,17070.00,NaN,NaN,35.73,91.28,CR-5,NaN,NaT,NaN,0,50인초과,서울특별시,3015 days,NaT,073645558,07-364-5558,07,364,5558,07-364-5558,07-364-5558
41196,73645558,G47911,2011-09-29,중기업,서울특별시 테헤란로4길,화장품,NaN,95.00,95.00,77.00,62.00,73.00,QAF201912401,지식재산금융센터,2019-12-31,직접,운전자금,기업일반자금대출,1160,500000000,0.00,0.00,5.00,4.00,1,혁신아이콘 Credit Line 건별심사,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-07-30,KRS-S,KR6,GR-1,NaN,FV-5,K6,II군,NaN,2018-12-31,49956.00,37111.00,35556.00,17070.00,NaN,NaN,35.73,91.28,CR-5,NaN,NaT,NaN,0,50인초과,서울특별시,3015 days,NaT,073645558,07-364-5558,07,364,5558,07-364-5558,07-364-5558

* 천단위 숫자 표현

In [31]:
# 천단위 숫자 표헌
base_data2['신규증액금액_comma']= base_data2['신규증액금액'].apply(lambda x: "{0:,}".format(x))
base_data2['신규증액금액'].describe()

count         41197.00
mean      286701315.41
std       523573319.74
min          126720.00
25%        99000000.00
50%       171000000.00
75%       285000000.00
max     10000000000.00
Name: 신규증액금액, dtype: float64

* 특정 칼럼 선택 : 다양한 방법

In [43]:
# 칼럼선택 방법

# 특정 컬럼 선택
test_table = base_data2.loc[:,['체크리스트저촉1','체크리스트저촉10']]
# test_table = base_data2.loc[:,'체크리스트저촉1','체크리스트저촉10']# error
# test_table = base_data2[['체크리스트저촉1','체크리스트저촉10']]
# test_table = base_data2['체크리스트저촉1','체크리스트저촉10'] # error

# 컬럼 범주 선택 => loc만 가능
# test_table = base_data2.loc[:,'체크리스트저촉1':'체크리스트저촉10']
# test_table = base_data2['체크리스트저촉1':'체크리스트저촉10'] # error
# test_table = base_data2[['체크리스트저촉1':'체크리스트저촉10']] # SyntaxError: invalid syntax

test_table

,체크리스트저촉1,체크리스트저촉10
0,미래상환능력 평가등급이 E등급 이하 (최근2개년 EBITDA이자보상배율이 계속 1미만),
1,당기 매출액대비 총차입금비율이 70% 초과,
2,"신청기업 최근 6개월 이내 주요국세(부가세,법인세,종합소득세) 체납",
3,NaN,NaN
4,NaN,NaN
...,...,...
41192,NaN,NaN
41193,"기업가치가 ""0""이하인 기업 또는 기업가치평가등급이 ""FV-10""인 기업",
41194,"기업가치가 ""0""이하인 기업 또는 기업가치평가등급이 ""FV-10""인 기업",
41195,NaN,NaN
41196,NaN,NaN

* list vs dataframe 비교

In [44]:
# 문자열 list vs dataframe 구분
a = ['사과','배','포도']
a[0]
# a[[0]] # TypeError: list indices must be integers or slices, not list
# a['사과'] # TypeError: list indices must be integers or slices, not str

'사과'

* 관심있는 행 찾기

In [27]:
# <관심있는 행 찾기>

find = base_data2.loc[base_data2['grade']=='AS15']
find.head()

,고객번호,최종업종코드,설립일자,기업규모,사업장소재지,판매품목1,판매품목2,피보험자수_취급월,피보험자수_기준월,피보험자수_전년말,피보험자수_전전년말,피보험자수_전전전년말,원장번호,취급부점,보증취급일자,직위재구분,자금용도,주채무과목,순보증사용일수,신규증액금액,심사서상_기보보증잔액,심사서상_재단보증잔액,상품정보_기업특성개수,상품정보_자금특성개수,CNT,심사종류,심사체크리스트저촉건수,체크리스트저촉1,체크리스트저촉2,체크리스트저촉3,체크리스트저촉4,체크리스트저촉5,체크리스트저촉6,체크리스트저촉7,체크리스트저촉8,체크리스트저촉9,체크리스트저촉10,조사기준일자,평가모형,grade,지식자산평가GR등급,기술평가TR등급,기업가치FV등급,보증심사등급,미래성장기업군,책임경영등급코드,(취급시)_당기_최종결산일자,(취급시)_당기_매출액,(취급시)_전기_매출액,(취급시)_당기_자산총계,(취급시)_전기_자산총계,(취급시)_당기_경상개발비,(취급시)_전기_경상개발비,(취급시)_당기_부채비율,(취급시)_전기_부채비율,(취급시)_당기_현금흐름등급,(취급시)_전기_현금흐름등급,부실사유발생일자,직접위탁부실발생금액_고객,부실여부,피보험자수_구분,지역구분,업력,부실기간
12827,62370734,M71600,2000-12-22,중기업,경기 팔달구,청소용역 외,NaN,14.00,9.00,20.00,64.00,48.00,TID201912367,경기영업본부,2019-04-30,직접,운전자금,기업일반자금대출,3600,300000000,0.00,68.00,1.00,3.00,1,정책보증/사회적경제보증심사,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-04-29,ARS,AS15,NaN,NaN,NaN,NaN,NaN,D,2018-12-31,1157.00,1412.00,513.00,524.00,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,0,20인이하,경기,6703 days,NaT